name: 'Unit tests'
description: 'Unit tests'
runs:
  using: 'composite'
  steps:
    - uses: ./.github/workflows/actions/playwright

    - name: Test
      shell: bash
      run: pnpm run test --cache-dir=.turbo
