name: 'Unit tests'
description: 'Unit tests'
runs:
  using: 'composite'
  steps:
    - name: Build
      shell: bash
      run: pnpm run build --cache-dir=.turbo

    - name: Test
      uses: ./.github/workflows/actions/playwright-container
      with:
        run: pnpm run test --cache-dir=.turbo --only
