name: 'Install dependencies'
description: 'Install dependencies'
runs:
  using: 'composite'
  steps:
    - name: Remove .npmrc
      run: rm .npmrc
      shell: bash

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
        scope: '@siemens'

    - name: configure yarnrc
      run: |
        echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
        echo 'yarn-offline-mirror-pruning true' >> .yarnrc
      shell: bash

    - uses: actions/cache@v3
      id: cache
      with:
        key: yarn-${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
        path: |
          .yarn-cache
          node_modules
          packages/**/node_modules

    - name: install
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --no-progress
      shell: bash
