packages:
  - packages/*
  - tooling/*
  - testing/*

catalog:
  '@esbuild/linux-arm64': 0.25.5
  '@playwright/test': 1.54.1
  glob: ^13.0.0
  vite: ^7.3.1

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@siemens/*'
