packages:
  - packages/*
  - tooling/*
  - testing/*

catalog:
  '@esbuild/linux-arm64': 0.27.2
  '@playwright/test': ^1.58.1
  '@axe-core/playwright': ^4.11.0
  '@siemens/ix-icons': ^3.3.0
  glob: ^13.0.0
  playwright: ^1.58.1
  vite: ^7.3.1
  eslint: ^9.39.3

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@siemens/*'
