packages:
  - packages/*
  - tooling/*
  - testing/*

catalog:
  '@esbuild/linux-arm64': 0.25.5
  '@playwright/test': ^1.54.1
  vite: 7.3.1
  playwright: ^1.57.0

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@siemens/*'
