/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
/* Generated with @siemens-ix/design-tokens@0.12.0. */
export const aggridIxThemeParams = {
  'accentColor': `var(--si-sys-color-effects-focus)`,
  'advancedFilterBuilderButtonBarBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-3)`,
  'advancedFilterBuilderColumnPillColor': `var(--si-sys-color-background-success-subtle)`,
  'advancedFilterBuilderJoinPillColor': `var(--si-sys-color-background-danger-subtle)`,
  'advancedFilterBuilderOptionPillColor': `var(--si-sys-color-background-critical-subtle)`,
  'advancedFilterBuilderValuePillColor': `var(--si-sys-color-background-information-subtle)`,
  'backgroundColor': `var(--si-sys-color-background-1)`,
  'borderColor': `var(--si-sys-color-border-4)`,
  'buttonActiveBackgroundColor': `var(--si-sys-color-background-active)`,
  'buttonActiveBorderColor': `var(--si-sys-color-border-2)`,
  'buttonActiveTextColor': `var(--si-sys-color-text-primary)`,
  'buttonBackgroundColor': `transparent`,
  'buttonBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-2)`,
  'buttonBorderColor': `var(--si-sys-color-border-2)`,
  'buttonDisabledBackgroundColor': `transparent`,
  'buttonDisabledBorderColor': `var(--si-sys-color-background-1)`,
  'buttonDisabledTextColor': `var(--si-sys-color-text-disabled)`,
  'buttonHoverBackgroundColor': `var(--si-sys-color-background-hover)`,
  'buttonHoverBorderColor': `var(--si-sys-color-border-2)`,
  'buttonHoverTextColor': `var(--si-sys-color-text-primary)`,
  'buttonTextColor': `var(--si-sys-color-text-primary)`,
  'cellEditingBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-accent-hover)`,
  'cellTextColor': `var(--si-sys-color-text-primary)`,
  'chartBackgroundColor': `var(--si-sys-color-background-0)`,
  'checkboxCheckedBackgroundColor': `var(--si-sys-color-background-accent-hover)`,
  'checkboxCheckedColor': `var(--si-sys-color-background-accent-hover)`,
  'checkboxCheckedShapeColor': `var(--si-sys-color-text-on-accent)`,
  'checkboxIndeterminateBackgroundColor': `var(--si-sys-color-background-accent-hover)`,
  'checkboxIndeterminateShapeColor': `var(--si-sys-color-text-on-accent)`,
  'checkboxUncheckedBackgroundColor': `var(--si-sys-color-background-accent-secondary)`,
  'checkboxUncheckedBorderColor': `var(--si-sys-color-border-1)`,
  'columnBorder': `false`,
  'columnDropCellBackgroundColor': `var(--si-sys-color-background-1)`,
  'columnDropCellBorder': `var(--theme-border-width-default) solid transparent`,
  'columnDropCellDragHandleColor': `var(--si-sys-color-text-primary)`,
  'columnDropCellTextColor': `var(--si-sys-color-text-primary)`,
  'columnHoverColor': `var(--si-sys-color-background-hover)`,
  'dialogBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-2)`,
  'dragAndDropImageBackgroundColor': `var(--si-sys-color-background-1)`,
  'dragAndDropImageBorder': `false`,
  'dragHandleColor': `var(--si-sys-color-text-primary)`,
  'footerRowBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-2)`,
  'foregroundColor': `var(--si-sys-color-text-primary)`,
  'headerBackgroundColor': `var(--si-sys-color-background-1)`,
  'headerCellHoverBackgroundColor': `var(--si-sys-color-background-hover)`,
  'headerColumnBorder': `false`,
  'headerColumnResizeHandleColor': `transparent`,
  'headerColumnResizeHandleHeight': `100%`,
  'headerColumnResizeHandleWidth': `var(--theme-border-width-default)`,
  'headerFontWeight': `700`,
  'headerRowBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-3)`,
  'icon': `true`,
  'iconButtonActiveBackgroundColor': `var(--si-sys-color-background-active)`,
  'iconButtonActiveColor': `var(--si-sys-color-text-accent-hover)`,
  'iconButtonActiveIndicatorColor': `var(--si-sys-color-text-accent-hover)`,
  'iconButtonBackgroundColor': `transparent`,
  'iconButtonColor': `var(--si-sys-color-text-primary)`,
  'iconButtonHoverBackgroundColor': `var(--si-sys-color-background-hover)`,
  'iconButtonHoverColor': `var(--si-sys-color-text-primary)`,
  'iconColor': `var(--si-sys-color-text-primary)`,
  'inputBackgroundColor': `var(--si-sys-color-background-1)`,
  'inputBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-2)`,
  'inputDisabledBackgroundColor': `transparent`,
  'inputDisabledBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-4)`,
  'inputDisabledBorderColor': `var(--si-sys-color-border-4)`,
  'inputDisabledTextColor': `var(--si-sys-color-text-disabled)`,
  'inputFocusBorder': `var(--theme-focus-border-thickness) solid var(--si-sys-color-effects-focus)`,
  'inputIconColor': `var(--si-sys-color-text-primary)`,
  'inputInvalidBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-danger)`,
  'inputInvalidBorderColor': `var(--si-sys-color-border-danger)`,
  'inputTextColor': `var(--si-sys-color-text-primary)`,
  'invalidColor': `var(--si-sys-color-text-danger)`,
  'menuBackgroundColor': `var(--si-sys-color-background-1)`,
  'menuBorder': `false`,
  'menuShadow': `var(--si-sys-color-effects-shadow-4)`,
  'oddRowBackgroundColor': `var(--si-sys-color-background-2)`,
  'panelTitleBarBorder': `false`,
  'pickerButtonBackgroundColor': `var(--si-sys-color-background-2)`,
  'pickerListBackgroundColor': `var(--si-sys-color-background-3)`,
  'pinnedColumnBackgroundColor': `var(--si-sys-color-background-active)`,
  'pinnedColumnBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-4)`,
  'pinnedRowBackgroundColor': `var(--si-sys-color-background-active)`,
  'pinnedRowBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-4)`,
  'rangeHeaderHighlightColor': `var(--si-sys-color-background-1)`,
  'rangeSelectionBackgroundColor': `var(--si-sys-color-background-active)`,
  'rangeSelectionBorderColor': `var(--si-sys-color-border-accent-hover)`,
  'rangeSelectionHighlightColor': `var(--si-sys-color-background-hover)`,
  'rowBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-4)`,
  'rowHoverColor': `var(--si-sys-color-background-hover)`,
  'rowLoadingSkeletonEffectColor': `var(--si-sys-color-background-hover)`,
  'selectCellBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-4)`,
  'selectedRowBackgroundColor': `var(--si-sys-color-background-active)`,
  'sideBarBackgroundColor': `var(--si-sys-color-background-1)`,
  'sideButtonHoverBackgroundColor': `var(--si-sys-color-background-hover)`,
  'sideButtonsBackgroundColor': `transparent`,
  'sideButtonsBarBackgroundColor': `var(--si-sys-color-background-1)`,
  'sideButtonSelectedBackgroundColor': `var(--si-sys-color-background-active)`,
  'sideButtonSelectedBorder': `false`,
  'sideButtonSelectedUnderlineColor': `var(--si-sys-color-background-active)`,
  'sidePanelBorder': `var(--theme-border-width-default) solid var(--si-sys-color-border-4)`,
  'statusBarLabelColor': `var(--si-sys-color-text-primary)`,
  'statusBarValueColor': `var(--si-sys-color-text-primary)`,
  'subtleTextColor': `var(--si-sys-color-text-secondary)`,
  'tabBackgroundColor': `transparent`,
  'tabBarBackgroundColor': `var(--si-sys-color-background-1)`,
  'tabBarBorder': `false`,
  'tabHoverBackgroundColor': `var(--si-sys-color-background-hover)`,
  'tabSelectedTextColor': `var(--si-sys-color-text-accent-hover)`,
  'tabSelectedUnderlineColor': `transparent`,
  'toggleButtonOffBackgroundColor': `var(--si-sys-color-background-neutral)`,
  'toggleButtonOnBackgroundColor': `var(--si-sys-color-background-accent-hover)`,
  'toggleButtonSwitchBackgroundColor': `var(--si-sys-color-background-0)`,
  'toolPanelSeparatorBorder': `false`,
  'tooltipBackgroundColor': `var(--si-sys-color-background-1)`,
  'tooltipBorder': `false`,
  'valueChangeDeltaDownColor': `var(--si-sys-color-text-danger)`,
  'valueChangeDeltaUpColor': `var(--si-sys-color-text-success)`,
  'valueChangeValueHighlightBackgroundColor': `var(--si-sys-color-background-active)`,
  'wrapperBorder': `false`,
};
