export const aggridIxThemeParams = {
  accentColor: `var(--theme-color-focus-bdr)`,
  backgroundColor: `var(--theme-color-0)`,
  foregroundColor: `var(--theme-color-std-text)`,
  cellTextColor: `var(--theme-color-std-text)`,
  headerCellHoverBackgroundColor: `var(--theme-color-ghost--hover)`,
  advancedFilterBuilderJoinPillColor: `var(--theme-color-alarm-40)`,
  advancedFilterBuilderColumnPillColor: `var(--theme-color-success-40)`,
  advancedFilterBuilderOptionPillColor: `var(--theme-color-critical-40)`,
  advancedFilterBuilderValuePillColor: `var(--theme-color-info-40)`,
  selectedRowBackgroundColor: `var(--theme-color-ghost--selected)`,
  rowHoverColor: `var(--theme-color-ghost--hover)`,
  columnHoverColor: `rgba(33, 150, 243, 0.5)`,
  rangeSelectionBackgroundColor: `var(--theme-color-ghost--selected)`,
  rangeSelectionHighlightColor: `var(--theme-color-ghost--selected-hover)`,
  borderColor: `var(--theme-color-soft-bdr)`,
  headerBackgroundColor: `var(--theme-color-0)`,
  tooltipBackgroundColor: `#fafbfb`,
  OddRowBackgroundColor: `var(--theme-color-ghost-alt)`,
  sideBarBackgroundColor: `var(--theme-color-1)`,
  invalidColor: `var(--theme-color-alarm)`,
  checkboxUncheckedBorderColor: `var(--theme-color-contrast-bdr)`,
  checkboxCheckedBackgroundColor: `var(--theme-color-dynamic)`,
  checkboxCheckedColor: `var(--theme-color-dynamic)`,
  rangeSelectionBorderColor: `#2196f3`,
  sideButtonSelectedBackgroundColor: `rgba(255, 255, 255, 0)`,
  sideButtonSelectedUnderlineColor: `#2196f3`,
  valueChangeDeltaUpColor: `var(--theme-color-success)`,
  valueChangeDeltaDownColor: `var(--theme-color-alarm)`,
  inputBackgroundColor: `var(--theme-color-component-8)`,
  inputDisabledBackgroundColor: `var(--theme-color-component-8)`,
  inputBorderColor: `var(--theme-color-std-bdr)`,
  inputDisabledBorder: `var(--theme-color-weak-bdr)`,
  inputFocusBorderColor: `var(--theme-color-focus-bdr)`,
  inputInvalidBorderColor: `var(--theme-color-alarm)`,
  inputTextColor: `var(--theme-color-std-text)`,
  inputDisabledTextColor: `var(--theme-color-weak-text)`,
  buttonBackgroundColor: `var(--theme-color-primary)`,
  buttonBorderColor: `var(--theme-color-ghost)`,
  buttonTextColor: `var(--theme-color-primary--contrast)`,
  buttonDisabledBackgroundColor: `var(--theme-color-component-4)`,
  buttonDisabledBorderColor: `var(--theme-color-ghost)`,
  buttonDisabledTextColor: `var(--theme-color-primary--contrast)`,
  buttonHoverBackgroundColor: `var(--theme-color-primary--hover)`,
  buttonHoverBorderColor: `var(--theme-color-ghost)`,
  buttonHoverTextColor: `var(--theme-color-primary--contrast)`,
  buttonActiveBackgroundColor: `var(--theme-color-primary--active)`,
  buttonActiveBorderColor: `var(--theme-color-ghost)`,
  buttonActiveTextColor: `var(--theme-color-primary--contrast)`,
  toggleButtonSwitchBackgroundColor: `var(--theme-color-1)`,
  toggleButtonOffBackgroundColor: `var(--theme-color-component-4)`,
  toggleButtonOnBackgroundColor: `var(--theme-color-dynamic)`,
  iconColor: `var(--theme-color-dynamic)`,
  tabBackgroundColor: `rgba(255, 255, 255, 0)`,
  tabBorderColor: `rgba(24, 29, 31, 0.15)`,
  tabHoverBackgroundColor: `rgba(255, 255, 255, 0)`,
  menuBackgroundColor: `#f8f8f8`,
  sideButtonsBackgroundColor: `rgba(255, 255, 255, 0)`,
  footerRowBorderColor: `var(--theme-color-std-bdr)`,
  pinnedRowBorderColor: `rgba(24, 29, 31, 0.15)`,
  columnBorderColor: `rgba(255, 255, 255, 0)`,
  inputDisabledBorderColor: `var(--theme-color-weak-bdr)`,
  dialogBorderColor: `var(--theme-color-std-bdr)`,
  selectCellBorderColor: `rgba(31, 28, 24, 0.13)`,
  advancedFilterBuilderButtonBarBorderColor: `var(--theme-color-soft-bdr)`,
  columnDropCellBorderColor: `var(--theme-color-ghost)`,
  wrapperBorderColor: `rgba(24, 29, 31, 0.15)`,
  tabBarBorderColor: `rgba(24, 29, 31, 0.15)`,
  dragAndDropImageBorderColor: `var(--theme-color-std-bdr)`,
  toolPanelSeparatorBorderColor: `rgba(24, 29, 31, 0.15)`,
  panelTitleBarBorderColor: `rgba(24, 29, 31, 0.15)`,
  pinnedColumnBorderColor: `rgba(24, 29, 31, 0.15)`,
  headerRowBorderColor: `var(--theme-color-soft-bdr)`,
  headerColumnBorderColor: `var(--theme-color-0)`,
  tooltipBorderColor: `#181d1f`,
  sideButtonSelectedBorderColor: `rgba(24, 29, 31, 0.15)`,
  cellEditingBorderColor: `var(--theme-color-dynamic)`,
  rowBorderColor: `var(--theme-color-weak-bdr)`,
  menuBorderColor: `var(--theme-color-std-bdr)`,
  sidePanelBorderColor: `var(--theme-color-std-bdr)`,
  checkboxUncheckedBackgroundColor: `var(--theme-color-secondary)`,
  checkboxIndeterminateShapeColor: `var(--theme-color-primary--contrast)`,
  valueChangeValueHighlightBackgroundColor: `rgba(22, 160, 133, 0.5)`,
  columnDropCellDragHandleColor: `var(--theme-color-std-text)`,
  columnDropCellBackgroundColor: `var(--theme-color-component-1)`,
  columnDropCellTextColor: `var(--theme-color-std-text)`,
  rowLoadingSkeletonEffectColor: `rgba(66, 66, 66, 0.2)`,
  tabBarBackgroundColor: `var(--theme-color-1)`,
  statusBarLabelColor: `#181d1f`,
  statusBarValueColor: `#181d1f`,
  dragAndDropImageBackgroundColor: `#ffffff`,
  inputIconColor: `var(--theme-color-std-text)`,
  dragHandleColor: `rgba(24, 29, 31, 0.7)`,
  iconButtonHoverBackgroundColor: `var(--theme-color-ghost--hover)`,
  iconButtonHoverColor: `var(--theme-color-std-text)`,
  iconButtonColor: `var(--theme-color-std-text)`,
  iconButtonActiveBackgroundColor: `var(--theme-color-ghost--active)`,
  iconButtonBackgroundColor: `var(--theme-color-ghost)`,
  iconButtonActiveColor: `var(--theme-color-dynamic)`,
  iconButtonActiveIndicatorColor: `var(--theme-color-dynamic)`,
  subtleTextColor: `rgba(24, 29, 31, 0.5)`,
  tabSelectedUnderlineColor: `rgba(255, 255, 255, 0)`,
  tabSelectedTextColor: `#181d1f`,
  advancedFilterBuilderButtonBarBorder: `var(--theme-color-soft-bdr)`,
  sideButtonsBarBackgroundColor: `#fafbfb`,
  sideButtonHoverBackgroundColor: `rgba(255, 255, 255, 0)`,
  checkboxCheckedShapeColor: `var(--theme-color-primary--contrast)`,
  chartBackgroundColor: `#ffffff`,
  'icon-alpine': `true`,
  'icon-quartz': `false`,
};
