name: 'Use build cache'
description: 'Use build cache'
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v3
      id: build-cache
      with:
        key: build-${{ runner.os }}-${{ github.sha }}
        path: |
          packages/**/dist
          packages/**/www
          packages/**/loader
          packages/**/build
          packages/**/components
