name: 'Execute unit tests'
description: 'Execute unit tests'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
        scope: '@siemens'

    - uses: actions/cache@v3
      id: cache
      with:
        key: yarn-${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
        path: |
          .yarn-cache
          node_modules
          packages/**/node_modules

    - name: Lint
      run: yarn lint
      shell: bash
