/*
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { testIds as HTMLPreviewTestIds } from './test-ids.autogenerated';

const excludedTestIds = ['aria-label-properties', 'divider'];
const additionalTestIds = ['form-validation'] as const;
const testIds = [...HTMLPreviewTestIds, ...additionalTestIds] as const;

export { HTMLPreviewTestIds, testIds, excludedTestIds };
