name: Bug Report
description: Found a bug in our library 📚
labels: ['type: bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        - Do not leak any internal company information!
        - Do not post internal links or code snippets!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: What type of frontend frameware are you seeing the problem on?
      multiple: true
      options:
        - Angular
        - React
        - JavaScript
        - Others
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Which version of ix do you use?
      description: Type the version here.
      placeholder: v1.x.x
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Code to produce this issue.
      description: Please copy and paste any relevant code to re-produce this issue.
      render: shell
