name: Bug Report for the official iX documentation
description: Documentation bug report 📑
labels: ['component: documentation', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Prerequisites
      description:  Make sure to not violate these rules
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
          required: true
        - label: I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here.
      placeholder: Tell us what you see!
    validations:
      required: true
