/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@siemens/ix/components';

import { defineCustomElement as defineIxActionCard } from '@siemens/ix/components/ix-action-card.js';
import { defineCustomElement as defineIxApplication } from '@siemens/ix/components/ix-application.js';
import { defineCustomElement as defineIxApplicationHeader } from '@siemens/ix/components/ix-application-header.js';
import { defineCustomElement as defineIxAvatar } from '@siemens/ix/components/ix-avatar.js';
import { defineCustomElement as defineIxBasicNavigation } from '@siemens/ix/components/ix-basic-navigation.js';
import { defineCustomElement as defineIxBlind } from '@siemens/ix/components/ix-blind.js';
import { defineCustomElement as defineIxBreadcrumb } from '@siemens/ix/components/ix-breadcrumb.js';
import { defineCustomElement as defineIxBreadcrumbItem } from '@siemens/ix/components/ix-breadcrumb-item.js';
import { defineCustomElement as defineIxButton } from '@siemens/ix/components/ix-button.js';
import { defineCustomElement as defineIxCard } from '@siemens/ix/components/ix-card.js';
import { defineCustomElement as defineIxCardAccordion } from '@siemens/ix/components/ix-card-accordion.js';
import { defineCustomElement as defineIxCardContent } from '@siemens/ix/components/ix-card-content.js';
import { defineCustomElement as defineIxCardList } from '@siemens/ix/components/ix-card-list.js';
import { defineCustomElement as defineIxCardTitle } from '@siemens/ix/components/ix-card-title.js';
import { defineCustomElement as defineIxCategoryFilter } from '@siemens/ix/components/ix-category-filter.js';
import { defineCustomElement as defineIxChip } from '@siemens/ix/components/ix-chip.js';
import { defineCustomElement as defineIxCol } from '@siemens/ix/components/ix-col.js';
import { defineCustomElement as defineIxContent } from '@siemens/ix/components/ix-content.js';
import { defineCustomElement as defineIxContentHeader } from '@siemens/ix/components/ix-content-header.js';
import { defineCustomElement as defineIxCustomField } from '@siemens/ix/components/ix-custom-field.js';
import { defineCustomElement as defineIxDateDropdown } from '@siemens/ix/components/ix-date-dropdown.js';
import { defineCustomElement as defineIxDateField } from '@siemens/ix/components/ix-date-field.js';
import { defineCustomElement as defineIxDatePicker } from '@siemens/ix/components/ix-date-picker.js';
import { defineCustomElement as defineIxDatetimePicker } from '@siemens/ix/components/ix-datetime-picker.js';
import { defineCustomElement as defineIxDivider } from '@siemens/ix/components/ix-divider.js';
import { defineCustomElement as defineIxDrawer } from '@siemens/ix/components/ix-drawer.js';
import { defineCustomElement as defineIxDropdown } from '@siemens/ix/components/ix-dropdown.js';
import { defineCustomElement as defineIxDropdownButton } from '@siemens/ix/components/ix-dropdown-button.js';
import { defineCustomElement as defineIxDropdownHeader } from '@siemens/ix/components/ix-dropdown-header.js';
import { defineCustomElement as defineIxDropdownItem } from '@siemens/ix/components/ix-dropdown-item.js';
import { defineCustomElement as defineIxDropdownQuickActions } from '@siemens/ix/components/ix-dropdown-quick-actions.js';
import { defineCustomElement as defineIxEmptyState } from '@siemens/ix/components/ix-empty-state.js';
import { defineCustomElement as defineIxEventList } from '@siemens/ix/components/ix-event-list.js';
import { defineCustomElement as defineIxEventListItem } from '@siemens/ix/components/ix-event-list-item.js';
import { defineCustomElement as defineIxExpandingSearch } from '@siemens/ix/components/ix-expanding-search.js';
import { defineCustomElement as defineIxFilterChip } from '@siemens/ix/components/ix-filter-chip.js';
import { defineCustomElement as defineIxFlipTile } from '@siemens/ix/components/ix-flip-tile.js';
import { defineCustomElement as defineIxFlipTileContent } from '@siemens/ix/components/ix-flip-tile-content.js';
import { defineCustomElement as defineIxFormField } from '@siemens/ix/components/ix-form-field.js';
import { defineCustomElement as defineIxGroup } from '@siemens/ix/components/ix-group.js';
import { defineCustomElement as defineIxGroupContextMenu } from '@siemens/ix/components/ix-group-context-menu.js';
import { defineCustomElement as defineIxGroupItem } from '@siemens/ix/components/ix-group-item.js';
import { defineCustomElement as defineIxHelperTextWrapper } from '@siemens/ix/components/ix-helper-text-wrapper.js';
import { defineCustomElement as defineIxIconButton } from '@siemens/ix/components/ix-icon-button.js';
import { defineCustomElement as defineIxIconToggleButton } from '@siemens/ix/components/ix-icon-toggle-button.js';
import { defineCustomElement as defineIxInputGroup } from '@siemens/ix/components/ix-input-group.js';
import { defineCustomElement as defineIxKeyValue } from '@siemens/ix/components/ix-key-value.js';
import { defineCustomElement as defineIxKeyValueList } from '@siemens/ix/components/ix-key-value-list.js';
import { defineCustomElement as defineIxKpi } from '@siemens/ix/components/ix-kpi.js';
import { defineCustomElement as defineIxLayoutGrid } from '@siemens/ix/components/ix-layout-grid.js';
import { defineCustomElement as defineIxLinkButton } from '@siemens/ix/components/ix-link-button.js';
import { defineCustomElement as defineIxMapNavigation } from '@siemens/ix/components/ix-map-navigation.js';
import { defineCustomElement as defineIxMapNavigationOverlay } from '@siemens/ix/components/ix-map-navigation-overlay.js';
import { defineCustomElement as defineIxMenu } from '@siemens/ix/components/ix-menu.js';
import { defineCustomElement as defineIxMenuAbout } from '@siemens/ix/components/ix-menu-about.js';
import { defineCustomElement as defineIxMenuAboutItem } from '@siemens/ix/components/ix-menu-about-item.js';
import { defineCustomElement as defineIxMenuAboutNews } from '@siemens/ix/components/ix-menu-about-news.js';
import { defineCustomElement as defineIxMenuAvatar } from '@siemens/ix/components/ix-menu-avatar.js';
import { defineCustomElement as defineIxMenuAvatarItem } from '@siemens/ix/components/ix-menu-avatar-item.js';
import { defineCustomElement as defineIxMenuCategory } from '@siemens/ix/components/ix-menu-category.js';
import { defineCustomElement as defineIxMenuItem } from '@siemens/ix/components/ix-menu-item.js';
import { defineCustomElement as defineIxMenuSettings } from '@siemens/ix/components/ix-menu-settings.js';
import { defineCustomElement as defineIxMenuSettingsItem } from '@siemens/ix/components/ix-menu-settings-item.js';
import { defineCustomElement as defineIxMessageBar } from '@siemens/ix/components/ix-message-bar.js';
import { defineCustomElement as defineIxModal } from '@siemens/ix/components/ix-modal.js';
import { defineCustomElement as defineIxModalContent } from '@siemens/ix/components/ix-modal-content.js';
import { defineCustomElement as defineIxModalExample } from '@siemens/ix/components/ix-modal-example.js';
import { defineCustomElement as defineIxModalFooter } from '@siemens/ix/components/ix-modal-footer.js';
import { defineCustomElement as defineIxModalHeader } from '@siemens/ix/components/ix-modal-header.js';
import { defineCustomElement as defineIxPagination } from '@siemens/ix/components/ix-pagination.js';
import { defineCustomElement as defineIxPane } from '@siemens/ix/components/ix-pane.js';
import { defineCustomElement as defineIxPaneLayout } from '@siemens/ix/components/ix-pane-layout.js';
import { defineCustomElement as defineIxPill } from '@siemens/ix/components/ix-pill.js';
import { defineCustomElement as defineIxPushCard } from '@siemens/ix/components/ix-push-card.js';
import { defineCustomElement as defineIxRow } from '@siemens/ix/components/ix-row.js';
import { defineCustomElement as defineIxSelect } from '@siemens/ix/components/ix-select.js';
import { defineCustomElement as defineIxSelectItem } from '@siemens/ix/components/ix-select-item.js';
import { defineCustomElement as defineIxSlider } from '@siemens/ix/components/ix-slider.js';
import { defineCustomElement as defineIxSpinner } from '@siemens/ix/components/ix-spinner.js';
import { defineCustomElement as defineIxSplitButton } from '@siemens/ix/components/ix-split-button.js';
import { defineCustomElement as defineIxSplitButtonItem } from '@siemens/ix/components/ix-split-button-item.js';
import { defineCustomElement as defineIxTabItem } from '@siemens/ix/components/ix-tab-item.js';
import { defineCustomElement as defineIxTabs } from '@siemens/ix/components/ix-tabs.js';
import { defineCustomElement as defineIxTextField } from '@siemens/ix/components/ix-text-field.js';
import { defineCustomElement as defineIxTile } from '@siemens/ix/components/ix-tile.js';
import { defineCustomElement as defineIxTimePicker } from '@siemens/ix/components/ix-time-picker.js';
import { defineCustomElement as defineIxToast } from '@siemens/ix/components/ix-toast.js';
import { defineCustomElement as defineIxToastContainer } from '@siemens/ix/components/ix-toast-container.js';
import { defineCustomElement as defineIxToggle } from '@siemens/ix/components/ix-toggle.js';
import { defineCustomElement as defineIxToggleButton } from '@siemens/ix/components/ix-toggle-button.js';
import { defineCustomElement as defineIxTooltip } from '@siemens/ix/components/ix-tooltip.js';
import { defineCustomElement as defineIxTypography } from '@siemens/ix/components/ix-typography.js';
import { defineCustomElement as defineIxUpload } from '@siemens/ix/components/ix-upload.js';
import { defineCustomElement as defineIxValidationTooltip } from '@siemens/ix/components/ix-validation-tooltip.js';
import { defineCustomElement as defineIxWorkflowStep } from '@siemens/ix/components/ix-workflow-step.js';
import { defineCustomElement as defineIxWorkflowSteps } from '@siemens/ix/components/ix-workflow-steps.js';

export const IxActionCard = /*@__PURE__*/createReactComponent<JSX.IxActionCard, HTMLIxActionCardElement>('ix-action-card', undefined, undefined, defineIxActionCard);
export const IxApplication = /*@__PURE__*/createReactComponent<JSX.IxApplication, HTMLIxApplicationElement>('ix-application', undefined, undefined, defineIxApplication);
export const IxApplicationHeader = /*@__PURE__*/createReactComponent<JSX.IxApplicationHeader, HTMLIxApplicationHeaderElement>('ix-application-header', undefined, undefined, defineIxApplicationHeader);
export const IxAvatar = /*@__PURE__*/createReactComponent<JSX.IxAvatar, HTMLIxAvatarElement>('ix-avatar', undefined, undefined, defineIxAvatar);
export const IxBasicNavigation = /*@__PURE__*/createReactComponent<JSX.IxBasicNavigation, HTMLIxBasicNavigationElement>('ix-basic-navigation', undefined, undefined, defineIxBasicNavigation);
export const IxBlind = /*@__PURE__*/createReactComponent<JSX.IxBlind, HTMLIxBlindElement>('ix-blind', undefined, undefined, defineIxBlind);
export const IxBreadcrumb = /*@__PURE__*/createReactComponent<JSX.IxBreadcrumb, HTMLIxBreadcrumbElement>('ix-breadcrumb', undefined, undefined, defineIxBreadcrumb);
export const IxBreadcrumbItem = /*@__PURE__*/createReactComponent<JSX.IxBreadcrumbItem, HTMLIxBreadcrumbItemElement>('ix-breadcrumb-item', undefined, undefined, defineIxBreadcrumbItem);
export const IxButton = /*@__PURE__*/createReactComponent<JSX.IxButton, HTMLIxButtonElement>('ix-button', undefined, undefined, defineIxButton);
export const IxCard = /*@__PURE__*/createReactComponent<JSX.IxCard, HTMLIxCardElement>('ix-card', undefined, undefined, defineIxCard);
export const IxCardAccordion = /*@__PURE__*/createReactComponent<JSX.IxCardAccordion, HTMLIxCardAccordionElement>('ix-card-accordion', undefined, undefined, defineIxCardAccordion);
export const IxCardContent = /*@__PURE__*/createReactComponent<JSX.IxCardContent, HTMLIxCardContentElement>('ix-card-content', undefined, undefined, defineIxCardContent);
export const IxCardList = /*@__PURE__*/createReactComponent<JSX.IxCardList, HTMLIxCardListElement>('ix-card-list', undefined, undefined, defineIxCardList);
export const IxCardTitle = /*@__PURE__*/createReactComponent<JSX.IxCardTitle, HTMLIxCardTitleElement>('ix-card-title', undefined, undefined, defineIxCardTitle);
export const IxCategoryFilter = /*@__PURE__*/createReactComponent<JSX.IxCategoryFilter, HTMLIxCategoryFilterElement>('ix-category-filter', undefined, undefined, defineIxCategoryFilter);
export const IxChip = /*@__PURE__*/createReactComponent<JSX.IxChip, HTMLIxChipElement>('ix-chip', undefined, undefined, defineIxChip);
export const IxCol = /*@__PURE__*/createReactComponent<JSX.IxCol, HTMLIxColElement>('ix-col', undefined, undefined, defineIxCol);
export const IxContent = /*@__PURE__*/createReactComponent<JSX.IxContent, HTMLIxContentElement>('ix-content', undefined, undefined, defineIxContent);
export const IxContentHeader = /*@__PURE__*/createReactComponent<JSX.IxContentHeader, HTMLIxContentHeaderElement>('ix-content-header', undefined, undefined, defineIxContentHeader);
export const IxCustomField = /*@__PURE__*/createReactComponent<JSX.IxCustomField, HTMLIxCustomFieldElement>('ix-custom-field', undefined, undefined, defineIxCustomField);
export const IxDateDropdown = /*@__PURE__*/createReactComponent<JSX.IxDateDropdown, HTMLIxDateDropdownElement>('ix-date-dropdown', undefined, undefined, defineIxDateDropdown);
export const IxDateField = /*@__PURE__*/createReactComponent<JSX.IxDateField, HTMLIxDateFieldElement>('ix-date-field', undefined, undefined, defineIxDateField);
export const IxDatePicker = /*@__PURE__*/createReactComponent<JSX.IxDatePicker, HTMLIxDatePickerElement>('ix-date-picker', undefined, undefined, defineIxDatePicker);
export const IxDatetimePicker = /*@__PURE__*/createReactComponent<JSX.IxDatetimePicker, HTMLIxDatetimePickerElement>('ix-datetime-picker', undefined, undefined, defineIxDatetimePicker);
export const IxDivider = /*@__PURE__*/createReactComponent<JSX.IxDivider, HTMLIxDividerElement>('ix-divider', undefined, undefined, defineIxDivider);
export const IxDrawer = /*@__PURE__*/createReactComponent<JSX.IxDrawer, HTMLIxDrawerElement>('ix-drawer', undefined, undefined, defineIxDrawer);
export const IxDropdown = /*@__PURE__*/createReactComponent<JSX.IxDropdown, HTMLIxDropdownElement>('ix-dropdown', undefined, undefined, defineIxDropdown);
export const IxDropdownButton = /*@__PURE__*/createReactComponent<JSX.IxDropdownButton, HTMLIxDropdownButtonElement>('ix-dropdown-button', undefined, undefined, defineIxDropdownButton);
export const IxDropdownHeader = /*@__PURE__*/createReactComponent<JSX.IxDropdownHeader, HTMLIxDropdownHeaderElement>('ix-dropdown-header', undefined, undefined, defineIxDropdownHeader);
export const IxDropdownItem = /*@__PURE__*/createReactComponent<JSX.IxDropdownItem, HTMLIxDropdownItemElement>('ix-dropdown-item', undefined, undefined, defineIxDropdownItem);
export const IxDropdownQuickActions = /*@__PURE__*/createReactComponent<JSX.IxDropdownQuickActions, HTMLIxDropdownQuickActionsElement>('ix-dropdown-quick-actions', undefined, undefined, defineIxDropdownQuickActions);
export const IxEmptyState = /*@__PURE__*/createReactComponent<JSX.IxEmptyState, HTMLIxEmptyStateElement>('ix-empty-state', undefined, undefined, defineIxEmptyState);
export const IxEventList = /*@__PURE__*/createReactComponent<JSX.IxEventList, HTMLIxEventListElement>('ix-event-list', undefined, undefined, defineIxEventList);
export const IxEventListItem = /*@__PURE__*/createReactComponent<JSX.IxEventListItem, HTMLIxEventListItemElement>('ix-event-list-item', undefined, undefined, defineIxEventListItem);
export const IxExpandingSearch = /*@__PURE__*/createReactComponent<JSX.IxExpandingSearch, HTMLIxExpandingSearchElement>('ix-expanding-search', undefined, undefined, defineIxExpandingSearch);
export const IxFilterChip = /*@__PURE__*/createReactComponent<JSX.IxFilterChip, HTMLIxFilterChipElement>('ix-filter-chip', undefined, undefined, defineIxFilterChip);
export const IxFlipTile = /*@__PURE__*/createReactComponent<JSX.IxFlipTile, HTMLIxFlipTileElement>('ix-flip-tile', undefined, undefined, defineIxFlipTile);
export const IxFlipTileContent = /*@__PURE__*/createReactComponent<JSX.IxFlipTileContent, HTMLIxFlipTileContentElement>('ix-flip-tile-content', undefined, undefined, defineIxFlipTileContent);
export const IxFormField = /*@__PURE__*/createReactComponent<JSX.IxFormField, HTMLIxFormFieldElement>('ix-form-field', undefined, undefined, defineIxFormField);
export const IxGroup = /*@__PURE__*/createReactComponent<JSX.IxGroup, HTMLIxGroupElement>('ix-group', undefined, undefined, defineIxGroup);
export const IxGroupContextMenu = /*@__PURE__*/createReactComponent<JSX.IxGroupContextMenu, HTMLIxGroupContextMenuElement>('ix-group-context-menu', undefined, undefined, defineIxGroupContextMenu);
export const IxGroupItem = /*@__PURE__*/createReactComponent<JSX.IxGroupItem, HTMLIxGroupItemElement>('ix-group-item', undefined, undefined, defineIxGroupItem);
export const IxHelperTextWrapper = /*@__PURE__*/createReactComponent<JSX.IxHelperTextWrapper, HTMLIxHelperTextWrapperElement>('ix-helper-text-wrapper', undefined, undefined, defineIxHelperTextWrapper);
export const IxIconButton = /*@__PURE__*/createReactComponent<JSX.IxIconButton, HTMLIxIconButtonElement>('ix-icon-button', undefined, undefined, defineIxIconButton);
export const IxIconToggleButton = /*@__PURE__*/createReactComponent<JSX.IxIconToggleButton, HTMLIxIconToggleButtonElement>('ix-icon-toggle-button', undefined, undefined, defineIxIconToggleButton);
export const IxInputGroup = /*@__PURE__*/createReactComponent<JSX.IxInputGroup, HTMLIxInputGroupElement>('ix-input-group', undefined, undefined, defineIxInputGroup);
export const IxKeyValue = /*@__PURE__*/createReactComponent<JSX.IxKeyValue, HTMLIxKeyValueElement>('ix-key-value', undefined, undefined, defineIxKeyValue);
export const IxKeyValueList = /*@__PURE__*/createReactComponent<JSX.IxKeyValueList, HTMLIxKeyValueListElement>('ix-key-value-list', undefined, undefined, defineIxKeyValueList);
export const IxKpi = /*@__PURE__*/createReactComponent<JSX.IxKpi, HTMLIxKpiElement>('ix-kpi', undefined, undefined, defineIxKpi);
export const IxLayoutGrid = /*@__PURE__*/createReactComponent<JSX.IxLayoutGrid, HTMLIxLayoutGridElement>('ix-layout-grid', undefined, undefined, defineIxLayoutGrid);
export const IxLinkButton = /*@__PURE__*/createReactComponent<JSX.IxLinkButton, HTMLIxLinkButtonElement>('ix-link-button', undefined, undefined, defineIxLinkButton);
export const IxMapNavigation = /*@__PURE__*/createReactComponent<JSX.IxMapNavigation, HTMLIxMapNavigationElement>('ix-map-navigation', undefined, undefined, defineIxMapNavigation);
export const IxMapNavigationOverlay = /*@__PURE__*/createReactComponent<JSX.IxMapNavigationOverlay, HTMLIxMapNavigationOverlayElement>('ix-map-navigation-overlay', undefined, undefined, defineIxMapNavigationOverlay);
export const IxMenu = /*@__PURE__*/createReactComponent<JSX.IxMenu, HTMLIxMenuElement>('ix-menu', undefined, undefined, defineIxMenu);
export const IxMenuAbout = /*@__PURE__*/createReactComponent<JSX.IxMenuAbout, HTMLIxMenuAboutElement>('ix-menu-about', undefined, undefined, defineIxMenuAbout);
export const IxMenuAboutItem = /*@__PURE__*/createReactComponent<JSX.IxMenuAboutItem, HTMLIxMenuAboutItemElement>('ix-menu-about-item', undefined, undefined, defineIxMenuAboutItem);
export const IxMenuAboutNews = /*@__PURE__*/createReactComponent<JSX.IxMenuAboutNews, HTMLIxMenuAboutNewsElement>('ix-menu-about-news', undefined, undefined, defineIxMenuAboutNews);
export const IxMenuAvatar = /*@__PURE__*/createReactComponent<JSX.IxMenuAvatar, HTMLIxMenuAvatarElement>('ix-menu-avatar', undefined, undefined, defineIxMenuAvatar);
export const IxMenuAvatarItem = /*@__PURE__*/createReactComponent<JSX.IxMenuAvatarItem, HTMLIxMenuAvatarItemElement>('ix-menu-avatar-item', undefined, undefined, defineIxMenuAvatarItem);
export const IxMenuCategory = /*@__PURE__*/createReactComponent<JSX.IxMenuCategory, HTMLIxMenuCategoryElement>('ix-menu-category', undefined, undefined, defineIxMenuCategory);
export const IxMenuItem = /*@__PURE__*/createReactComponent<JSX.IxMenuItem, HTMLIxMenuItemElement>('ix-menu-item', undefined, undefined, defineIxMenuItem);
export const IxMenuSettings = /*@__PURE__*/createReactComponent<JSX.IxMenuSettings, HTMLIxMenuSettingsElement>('ix-menu-settings', undefined, undefined, defineIxMenuSettings);
export const IxMenuSettingsItem = /*@__PURE__*/createReactComponent<JSX.IxMenuSettingsItem, HTMLIxMenuSettingsItemElement>('ix-menu-settings-item', undefined, undefined, defineIxMenuSettingsItem);
export const IxMessageBar = /*@__PURE__*/createReactComponent<JSX.IxMessageBar, HTMLIxMessageBarElement>('ix-message-bar', undefined, undefined, defineIxMessageBar);
export const IxModal = /*@__PURE__*/createReactComponent<JSX.IxModal, HTMLIxModalElement>('ix-modal', undefined, undefined, defineIxModal);
export const IxModalContent = /*@__PURE__*/createReactComponent<JSX.IxModalContent, HTMLIxModalContentElement>('ix-modal-content', undefined, undefined, defineIxModalContent);
export const IxModalExample = /*@__PURE__*/createReactComponent<JSX.IxModalExample, HTMLIxModalExampleElement>('ix-modal-example', undefined, undefined, defineIxModalExample);
export const IxModalFooter = /*@__PURE__*/createReactComponent<JSX.IxModalFooter, HTMLIxModalFooterElement>('ix-modal-footer', undefined, undefined, defineIxModalFooter);
export const IxModalHeader = /*@__PURE__*/createReactComponent<JSX.IxModalHeader, HTMLIxModalHeaderElement>('ix-modal-header', undefined, undefined, defineIxModalHeader);
export const IxPagination = /*@__PURE__*/createReactComponent<JSX.IxPagination, HTMLIxPaginationElement>('ix-pagination', undefined, undefined, defineIxPagination);
export const IxPane = /*@__PURE__*/createReactComponent<JSX.IxPane, HTMLIxPaneElement>('ix-pane', undefined, undefined, defineIxPane);
export const IxPaneLayout = /*@__PURE__*/createReactComponent<JSX.IxPaneLayout, HTMLIxPaneLayoutElement>('ix-pane-layout', undefined, undefined, defineIxPaneLayout);
export const IxPill = /*@__PURE__*/createReactComponent<JSX.IxPill, HTMLIxPillElement>('ix-pill', undefined, undefined, defineIxPill);
export const IxPushCard = /*@__PURE__*/createReactComponent<JSX.IxPushCard, HTMLIxPushCardElement>('ix-push-card', undefined, undefined, defineIxPushCard);
export const IxRow = /*@__PURE__*/createReactComponent<JSX.IxRow, HTMLIxRowElement>('ix-row', undefined, undefined, defineIxRow);
export const IxSelect = /*@__PURE__*/createReactComponent<JSX.IxSelect, HTMLIxSelectElement>('ix-select', undefined, undefined, defineIxSelect);
export const IxSelectItem = /*@__PURE__*/createReactComponent<JSX.IxSelectItem, HTMLIxSelectItemElement>('ix-select-item', undefined, undefined, defineIxSelectItem);
export const IxSlider = /*@__PURE__*/createReactComponent<JSX.IxSlider, HTMLIxSliderElement>('ix-slider', undefined, undefined, defineIxSlider);
export const IxSpinner = /*@__PURE__*/createReactComponent<JSX.IxSpinner, HTMLIxSpinnerElement>('ix-spinner', undefined, undefined, defineIxSpinner);
export const IxSplitButton = /*@__PURE__*/createReactComponent<JSX.IxSplitButton, HTMLIxSplitButtonElement>('ix-split-button', undefined, undefined, defineIxSplitButton);
export const IxSplitButtonItem = /*@__PURE__*/createReactComponent<JSX.IxSplitButtonItem, HTMLIxSplitButtonItemElement>('ix-split-button-item', undefined, undefined, defineIxSplitButtonItem);
export const IxTabItem = /*@__PURE__*/createReactComponent<JSX.IxTabItem, HTMLIxTabItemElement>('ix-tab-item', undefined, undefined, defineIxTabItem);
export const IxTabs = /*@__PURE__*/createReactComponent<JSX.IxTabs, HTMLIxTabsElement>('ix-tabs', undefined, undefined, defineIxTabs);
export const IxTextField = /*@__PURE__*/createReactComponent<JSX.IxTextField, HTMLIxTextFieldElement>('ix-text-field', undefined, undefined, defineIxTextField);
export const IxTile = /*@__PURE__*/createReactComponent<JSX.IxTile, HTMLIxTileElement>('ix-tile', undefined, undefined, defineIxTile);
export const IxTimePicker = /*@__PURE__*/createReactComponent<JSX.IxTimePicker, HTMLIxTimePickerElement>('ix-time-picker', undefined, undefined, defineIxTimePicker);
export const IxToast = /*@__PURE__*/createReactComponent<JSX.IxToast, HTMLIxToastElement>('ix-toast', undefined, undefined, defineIxToast);
export const IxToastContainer = /*@__PURE__*/createReactComponent<JSX.IxToastContainer, HTMLIxToastContainerElement>('ix-toast-container', undefined, undefined, defineIxToastContainer);
export const IxToggle = /*@__PURE__*/createReactComponent<JSX.IxToggle, HTMLIxToggleElement>('ix-toggle', undefined, undefined, defineIxToggle);
export const IxToggleButton = /*@__PURE__*/createReactComponent<JSX.IxToggleButton, HTMLIxToggleButtonElement>('ix-toggle-button', undefined, undefined, defineIxToggleButton);
export const IxTooltip = /*@__PURE__*/createReactComponent<JSX.IxTooltip, HTMLIxTooltipElement>('ix-tooltip', undefined, undefined, defineIxTooltip);
export const IxTypography = /*@__PURE__*/createReactComponent<JSX.IxTypography, HTMLIxTypographyElement>('ix-typography', undefined, undefined, defineIxTypography);
export const IxUpload = /*@__PURE__*/createReactComponent<JSX.IxUpload, HTMLIxUploadElement>('ix-upload', undefined, undefined, defineIxUpload);
export const IxValidationTooltip = /*@__PURE__*/createReactComponent<JSX.IxValidationTooltip, HTMLIxValidationTooltipElement>('ix-validation-tooltip', undefined, undefined, defineIxValidationTooltip);
export const IxWorkflowStep = /*@__PURE__*/createReactComponent<JSX.IxWorkflowStep, HTMLIxWorkflowStepElement>('ix-workflow-step', undefined, undefined, defineIxWorkflowStep);
export const IxWorkflowSteps = /*@__PURE__*/createReactComponent<JSX.IxWorkflowSteps, HTMLIxWorkflowStepsElement>('ix-workflow-steps', undefined, undefined, defineIxWorkflowSteps);
