'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxApplicationHeaderCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxApplicationHeader as IxApplicationHeaderElement } from "@siemens/ix/components/ix-application-header.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxApplicationHeaderEvents = {
    onMenuToggle: EventName<IxApplicationHeaderCustomEvent<boolean>>,
    onOpenAppSwitch: EventName<IxApplicationHeaderCustomEvent<void>>
};

export const IxApplicationHeader: StencilReactComponent<IxApplicationHeaderElement, IxApplicationHeaderEvents, Components.IxApplicationHeader> = /*@__PURE__*/ createComponent<IxApplicationHeaderElement, IxApplicationHeaderEvents, Components.IxApplicationHeader>({
    tagName: 'ix-application-header',
    properties: {
        name: 'name',
        nameSuffix: 'name-suffix',
        companyLogo: 'company-logo',
        companyLogoAlt: 'company-logo-alt',
        appIcon: 'app-icon',
        appIconAlt: 'app-icon-alt',
        appIconOutline: 'app-icon-outline',
        hideBottomBorder: 'hide-bottom-border',
        showMenu: 'show-menu',
        ariaLabelMenuExpandIconButton: 'aria-label-menu-expand-icon-button',
        ariaLabelAppSwitchIconButton: 'aria-label-app-switch-icon-button',
        ariaLabelMoreMenuIconButton: 'aria-label-more-menu-icon-button',
        enableTopLayer: 'enable-top-layer'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxApplicationHeader as StencilReactComponent<IxApplicationHeaderElement, IxApplicationHeaderEvents, Components.IxApplicationHeader>,
    serializeShadowRoot
});
