'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxButton as IxButtonElement } from "@siemens/ix/components/ix-button.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxButtonEvents = NonNullable<unknown>;

export const IxButton: StencilReactComponent<IxButtonElement, IxButtonEvents, Components.IxButton> = /*@__PURE__*/ createComponent<IxButtonElement, IxButtonEvents, Components.IxButton>({
    tagName: 'ix-button',
    properties: {
        variant: 'variant',
        disabled: 'disabled',
        type: 'type',
        loading: 'loading',
        form: 'form',
        icon: 'icon',
        iconRight: 'icon-right',
        alignment: 'alignment',
        iconSize: 'icon-size',
        href: 'href',
        target: 'target',
        rel: 'rel'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxButton as StencilReactComponent<IxButtonElement, IxButtonEvents, Components.IxButton>,
    serializeShadowRoot
});
