'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxCol as IxColElement } from "@siemens/ix/components/ix-col.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxColEvents = NonNullable<unknown>;

export const IxCol: StencilReactComponent<IxColElement, IxColEvents, Components.IxCol> = /*@__PURE__*/ createComponent<IxColElement, IxColEvents, Components.IxCol>({
    tagName: 'ix-col',
    properties: {
        size: 'size',
        sizeSm: 'size-sm',
        sizeMd: 'size-md',
        sizeLg: 'size-lg'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxCol as StencilReactComponent<IxColElement, IxColEvents, Components.IxCol>,
    serializeShadowRoot
});
