'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type FilterState, type InputState, type IxCategoryFilterCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxCategoryFilter as IxCategoryFilterElement } from "@siemens/ix/components/ix-category-filter.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxCategoryFilterEvents = {
    onCategoryChanged: EventName<IxCategoryFilterCustomEvent<string>>,
    onInputChanged: EventName<IxCategoryFilterCustomEvent<InputState>>,
    onFilterChanged: EventName<IxCategoryFilterCustomEvent<FilterState>>,
    onFilterCleared: EventName<IxCategoryFilterCustomEvent<void>>
};

export const IxCategoryFilter: StencilReactComponent<IxCategoryFilterElement, IxCategoryFilterEvents, Components.IxCategoryFilter> = /*@__PURE__*/ createComponent<IxCategoryFilterElement, IxCategoryFilterEvents, Components.IxCategoryFilter>({
    tagName: 'ix-category-filter',
    properties: {
        disabled: 'disabled',
        readonly: 'readonly',
        placeholder: 'placeholder',
        icon: 'icon',
        hideIcon: 'hide-icon',
        staticOperator: 'static-operator',
        uniqueCategories: 'unique-categories',
        labelCategories: 'label-categories',
        i18nPlainText: 'i18n-plain-text',
        ariaLabelResetButton: 'aria-label-reset-button',
        ariaLabelOperatorButton: 'aria-label-operator-button',
        ariaLabelFilterInput: 'aria-label-filter-input',
        enableTopLayer: 'enable-top-layer'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxCategoryFilter as StencilReactComponent<IxCategoryFilterElement, IxCategoryFilterEvents, Components.IxCategoryFilter>,
    serializeShadowRoot
});
