'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxContentHeaderCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxContentHeader as IxContentHeaderElement } from "@siemens/ix/components/ix-content-header.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxContentHeaderEvents = { onBackButtonClick: EventName<IxContentHeaderCustomEvent<void>> };

export const IxContentHeader: StencilReactComponent<IxContentHeaderElement, IxContentHeaderEvents, Components.IxContentHeader> = /*@__PURE__*/ createComponent<IxContentHeaderElement, IxContentHeaderEvents, Components.IxContentHeader>({
    tagName: 'ix-content-header',
    properties: {
        variant: 'variant',
        headerTitle: 'header-title',
        headerSubtitle: 'header-subtitle',
        hasBackButton: 'has-back-button'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxContentHeader as StencilReactComponent<IxContentHeaderElement, IxContentHeaderEvents, Components.IxContentHeader>,
    serializeShadowRoot
});
