'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxChipCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxChip as IxChipElement, defineCustomElement as defineIxChip } from "@siemens/ix/components/ix-chip.js";

export type IxChipEvents = { onCloseChip: EventName<IxChipCustomEvent<any>> };

export const IxChip: StencilReactComponent<IxChipElement, IxChipEvents, Components.IxChip> = /*@__PURE__*/ createComponent<IxChipElement, IxChipEvents, Components.IxChip>({
    tagName: 'ix-chip',
    elementClass: IxChipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCloseChip: 'closeChip' } as IxChipEvents,
    defineCustomElement: defineIxChip
});
