'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type FilterState, type InputState, type IxCategoryFilterCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxCategoryFilter as IxCategoryFilterElement, defineCustomElement as defineIxCategoryFilter } from "@siemens/ix/components/ix-category-filter.js";

export type IxCategoryFilterEvents = {
    onCategoryChanged: EventName<IxCategoryFilterCustomEvent<string>>,
    onInputChanged: EventName<IxCategoryFilterCustomEvent<InputState>>,
    onFilterChanged: EventName<IxCategoryFilterCustomEvent<FilterState>>,
    onFilterCleared: EventName<IxCategoryFilterCustomEvent<void>>
};

export const IxCategoryFilter: StencilReactComponent<IxCategoryFilterElement, IxCategoryFilterEvents, Components.IxCategoryFilter> = /*@__PURE__*/ createComponent<IxCategoryFilterElement, IxCategoryFilterEvents, Components.IxCategoryFilter>({
    tagName: 'ix-category-filter',
    elementClass: IxCategoryFilterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCategoryChanged: 'categoryChanged',
        onInputChanged: 'inputChanged',
        onFilterChanged: 'filterChanged',
        onFilterCleared: 'filterCleared'
    } as IxCategoryFilterEvents,
    defineCustomElement: defineIxCategoryFilter
});
