'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxChipCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxChip as IxChipElement } from "@siemens/ix/components/ix-chip.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxChipEvents = { onCloseChip: EventName<IxChipCustomEvent<any>> };

export const IxChip: StencilReactComponent<IxChipElement, IxChipEvents, Components.IxChip> = /*@__PURE__*/ createComponent<IxChipElement, IxChipEvents, Components.IxChip>({
    tagName: 'ix-chip',
    properties: {
        variant: 'variant',
        inactive: 'inactive',
        closable: 'closable',
        icon: 'icon',
        ariaLabelIcon: 'aria-label-icon',
        background: 'background',
        chipColor: 'chip-color',
        outline: 'outline',
        tooltipText: 'tooltip-text',
        centerContent: 'center-content',
        ariaLabelCloseButton: 'aria-label-close-button'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxChip as StencilReactComponent<IxChipElement, IxChipEvents, Components.IxChip>,
    serializeShadowRoot
});
