'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxContentHeaderCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxContentHeader as IxContentHeaderElement, defineCustomElement as defineIxContentHeader } from "@siemens/ix/components/ix-content-header.js";

export type IxContentHeaderEvents = { onBackButtonClick: EventName<IxContentHeaderCustomEvent<void>> };

export const IxContentHeader: StencilReactComponent<IxContentHeaderElement, IxContentHeaderEvents, Components.IxContentHeader> = /*@__PURE__*/ createComponent<IxContentHeaderElement, IxContentHeaderEvents, Components.IxContentHeader>({
    tagName: 'ix-content-header',
    elementClass: IxContentHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBackButtonClick: 'backButtonClick' } as IxContentHeaderEvents,
    defineCustomElement: defineIxContentHeader
});
