'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type DateInputValidityState, type IxDateInputCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxDateInput as IxDateInputElement } from "@siemens/ix/components/ix-date-input.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxDateInputEvents = {
    onValueChange: EventName<IxDateInputCustomEvent<string | undefined>>,
    onValidityStateChange: EventName<IxDateInputCustomEvent<DateInputValidityState>>,
    onIxChange: EventName<IxDateInputCustomEvent<string | undefined>>
};

export const IxDateInput: StencilReactComponent<IxDateInputElement, IxDateInputEvents, Components.IxDateInput> = /*@__PURE__*/ createComponent<IxDateInputElement, IxDateInputEvents, Components.IxDateInput>({
    tagName: 'ix-date-input',
    properties: {
        name: 'name',
        placeholder: 'placeholder',
        value: 'value',
        minDate: 'min-date',
        maxDate: 'max-date',
        locale: 'locale',
        format: 'format',
        required: 'required',
        helperText: 'helper-text',
        label: 'label',
        ariaLabelCalendarButton: 'aria-label-calendar-button',
        invalidText: 'invalid-text',
        readonly: 'readonly',
        disabled: 'disabled',
        infoText: 'info-text',
        warningText: 'warning-text',
        validText: 'valid-text',
        showTextAsTooltip: 'show-text-as-tooltip',
        i18nErrorDateUnparsable: 'i18n-error-date-unparsable',
        showWeekNumbers: 'show-week-numbers',
        weekStartIndex: 'week-start-index',
        ariaLabelPreviousMonthButton: 'aria-label-previous-month-button',
        ariaLabelNextMonthButton: 'aria-label-next-month-button',
        suppressSubmitOnEnter: 'suppress-submit-on-enter',
        textAlignment: 'text-alignment',
        enableTopLayer: 'enable-top-layer'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxDateInput as StencilReactComponent<IxDateInputElement, IxDateInputEvents, Components.IxDateInput>,
    serializeShadowRoot
});
