'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type DateTimeInputValidityState, type IxDatetimeInputCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxDatetimeInput as IxDatetimeInputElement } from "@siemens/ix/components/ix-datetime-input.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxDatetimeInputEvents = {
    onValueChange: EventName<IxDatetimeInputCustomEvent<string | undefined>>,
    onValidityStateChange: EventName<IxDatetimeInputCustomEvent<DateTimeInputValidityState>>,
    onIxFocus: EventName<IxDatetimeInputCustomEvent<void>>,
    onIxBlur: EventName<IxDatetimeInputCustomEvent<void>>,
    onIxChange: EventName<IxDatetimeInputCustomEvent<string | undefined>>
};

export const IxDatetimeInput: StencilReactComponent<IxDatetimeInputElement, IxDatetimeInputEvents, Components.IxDatetimeInput> = /*@__PURE__*/ createComponent<IxDatetimeInputElement, IxDatetimeInputEvents, Components.IxDatetimeInput>({
    tagName: 'ix-datetime-input',
    properties: {
        name: 'name',
        placeholder: 'placeholder',
        value: 'value',
        format: 'format',
        locale: 'locale',
        required: 'required',
        disabled: 'disabled',
        readonly: 'readonly',
        minDate: 'min-date',
        maxDate: 'max-date',
        minTime: 'min-time',
        maxTime: 'max-time',
        label: 'label',
        helperText: 'helper-text',
        invalidText: 'invalid-text',
        infoText: 'info-text',
        warningText: 'warning-text',
        validText: 'valid-text',
        showTextAsTooltip: 'show-text-as-tooltip',
        i18nErrorDateTimeUnparsable: 'i-1-8n-error-date-time-unparsable',
        i18nDone: 'i-1-8n-done',
        i18nTime: 'i-1-8n-time',
        ariaLabelPreviousMonthButton: 'aria-label-previous-month-button',
        ariaLabelNextMonthButton: 'aria-label-next-month-button',
        ariaLabelCalendarButton: 'aria-label-calendar-button',
        showWeekNumbers: 'show-week-numbers',
        weekStartIndex: 'week-start-index',
        suppressSubmitOnEnter: 'suppress-submit-on-enter',
        textAlignment: 'text-alignment',
        enableTopLayer: 'enable-top-layer'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxDatetimeInput as StencilReactComponent<IxDatetimeInputElement, IxDatetimeInputEvents, Components.IxDatetimeInput>,
    serializeShadowRoot
});
