'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxDrawerCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxDrawer as IxDrawerElement } from "@siemens/ix/components/ix-drawer.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxDrawerEvents = {
    onOpen: EventName<IxDrawerCustomEvent<any>>,
    onDrawerClose: EventName<IxDrawerCustomEvent<any>>
};

export const IxDrawer: StencilReactComponent<IxDrawerElement, IxDrawerEvents, Components.IxDrawer> = /*@__PURE__*/ createComponent<IxDrawerElement, IxDrawerEvents, Components.IxDrawer>({
    tagName: 'ix-drawer',
    properties: {
        show: 'show',
        closeOnClickOutside: 'close-on-click-outside',
        fullHeight: 'full-height',
        minWidth: 'min-width',
        maxWidth: 'max-width',
        width: 'width',
        ariaLabelCloseButton: 'aria-label-close-button'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxDrawer as StencilReactComponent<IxDrawerElement, IxDrawerEvents, Components.IxDrawer>,
    serializeShadowRoot
});
