'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type DateInputValidityState, type IxDateInputCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxDateInput as IxDateInputElement, defineCustomElement as defineIxDateInput } from "@siemens/ix/components/ix-date-input.js";

export type IxDateInputEvents = {
    onValueChange: EventName<IxDateInputCustomEvent<string | undefined>>,
    onValidityStateChange: EventName<IxDateInputCustomEvent<DateInputValidityState>>,
    onIxChange: EventName<IxDateInputCustomEvent<string | undefined>>
};

export const IxDateInput: StencilReactComponent<IxDateInputElement, IxDateInputEvents, Components.IxDateInput> = /*@__PURE__*/ createComponent<IxDateInputElement, IxDateInputEvents, Components.IxDateInput>({
    tagName: 'ix-date-input',
    elementClass: IxDateInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueChange: 'valueChange',
        onValidityStateChange: 'validityStateChange',
        onIxChange: 'ixChange'
    } as IxDateInputEvents,
    defineCustomElement: defineIxDateInput
});
