'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxDropdownButtonCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxDropdownButton as IxDropdownButtonElement } from "@siemens/ix/components/ix-dropdown-button.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxDropdownButtonEvents = {
    onShowChange: EventName<IxDropdownButtonCustomEvent<boolean>>,
    onShowChanged: EventName<IxDropdownButtonCustomEvent<boolean>>
};

export const IxDropdownButton: StencilReactComponent<IxDropdownButtonElement, IxDropdownButtonEvents, Components.IxDropdownButton> = /*@__PURE__*/ createComponent<IxDropdownButtonElement, IxDropdownButtonEvents, Components.IxDropdownButton>({
    tagName: 'ix-dropdown-button',
    properties: {
        variant: 'variant',
        disabled: 'disabled',
        label: 'label',
        icon: 'icon',
        closeBehavior: 'close-behavior',
        placement: 'placement',
        ariaLabelDropdownButton: 'aria-label-dropdown-button',
        focusCheckedItem: 'focus-checked-item',
        enableTopLayer: 'enable-top-layer',
        suppressAriaActiveDescendant: 'suppress-aria-active-descendant'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxDropdownButton as StencilReactComponent<IxDropdownButtonElement, IxDropdownButtonEvents, Components.IxDropdownButton>,
    serializeShadowRoot
});
