'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxDropdownButtonCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxDropdownButton as IxDropdownButtonElement, defineCustomElement as defineIxDropdownButton } from "@siemens/ix/components/ix-dropdown-button.js";

export type IxDropdownButtonEvents = {
    onShowChange: EventName<IxDropdownButtonCustomEvent<boolean>>,
    onShowChanged: EventName<IxDropdownButtonCustomEvent<boolean>>
};

export const IxDropdownButton: StencilReactComponent<IxDropdownButtonElement, IxDropdownButtonEvents, Components.IxDropdownButton> = /*@__PURE__*/ createComponent<IxDropdownButtonElement, IxDropdownButtonEvents, Components.IxDropdownButton>({
    tagName: 'ix-dropdown-button',
    elementClass: IxDropdownButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onShowChange: 'showChange',
        onShowChanged: 'showChanged'
    } as IxDropdownButtonEvents,
    defineCustomElement: defineIxDropdownButton
});
