'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxEmptyStateCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxEmptyState as IxEmptyStateElement } from "@siemens/ix/components/ix-empty-state.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxEmptyStateEvents = { onActionClick: EventName<IxEmptyStateCustomEvent<void>> };

export const IxEmptyState: StencilReactComponent<IxEmptyStateElement, IxEmptyStateEvents, Components.IxEmptyState> = /*@__PURE__*/ createComponent<IxEmptyStateElement, IxEmptyStateEvents, Components.IxEmptyState>({
    tagName: 'ix-empty-state',
    properties: {
        layout: 'layout',
        icon: 'icon',
        header: 'header',
        subHeader: 'sub-header',
        action: 'action',
        ariaLabelEmptyStateIcon: 'aria-label-empty-state-icon'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxEmptyState as StencilReactComponent<IxEmptyStateElement, IxEmptyStateEvents, Components.IxEmptyState>,
    serializeShadowRoot
});
