'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxEventList as IxEventListElement } from "@siemens/ix/components/ix-event-list.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxEventListEvents = NonNullable<unknown>;

export const IxEventList: StencilReactComponent<IxEventListElement, IxEventListEvents, Components.IxEventList> = /*@__PURE__*/ createComponent<IxEventListElement, IxEventListEvents, Components.IxEventList>({
    tagName: 'ix-event-list',
    properties: {
        itemHeight: 'item-height',
        compact: 'compact',
        animated: 'animated',
        chevron: 'chevron'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxEventList as StencilReactComponent<IxEventListElement, IxEventListEvents, Components.IxEventList>,
    serializeShadowRoot
});
