'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxExpandingSearchCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxExpandingSearch as IxExpandingSearchElement, defineCustomElement as defineIxExpandingSearch } from "@siemens/ix/components/ix-expanding-search.js";

export type IxExpandingSearchEvents = { onValueChange: EventName<IxExpandingSearchCustomEvent<string>> };

export const IxExpandingSearch: StencilReactComponent<IxExpandingSearchElement, IxExpandingSearchEvents, Components.IxExpandingSearch> = /*@__PURE__*/ createComponent<IxExpandingSearchElement, IxExpandingSearchEvents, Components.IxExpandingSearch>({
    tagName: 'ix-expanding-search',
    elementClass: IxExpandingSearchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as IxExpandingSearchEvents,
    defineCustomElement: defineIxExpandingSearch
});
