'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxFilterChipCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxFilterChip as IxFilterChipElement } from "@siemens/ix/components/ix-filter-chip.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxFilterChipEvents = { onCloseClick: EventName<IxFilterChipCustomEvent<void>> };

export const IxFilterChip: StencilReactComponent<IxFilterChipElement, IxFilterChipEvents, Components.IxFilterChip> = /*@__PURE__*/ createComponent<IxFilterChipElement, IxFilterChipEvents, Components.IxFilterChip>({
    tagName: 'ix-filter-chip',
    properties: {
        disabled: 'disabled',
        readonly: 'readonly',
        ariaLabelCloseIconButton: 'aria-label-close-icon-button'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxFilterChip as StencilReactComponent<IxFilterChipElement, IxFilterChipEvents, Components.IxFilterChip>,
    serializeShadowRoot
});
