'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxFlipTileCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxFlipTile as IxFlipTileElement, defineCustomElement as defineIxFlipTile } from "@siemens/ix/components/ix-flip-tile.js";

export type IxFlipTileEvents = { onToggle: EventName<IxFlipTileCustomEvent<number>> };

export const IxFlipTile: StencilReactComponent<IxFlipTileElement, IxFlipTileEvents, Components.IxFlipTile> = /*@__PURE__*/ createComponent<IxFlipTileElement, IxFlipTileEvents, Components.IxFlipTile>({
    tagName: 'ix-flip-tile',
    elementClass: IxFlipTileElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onToggle: 'toggle' } as IxFlipTileEvents,
    defineCustomElement: defineIxFlipTile
});
