'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxGroupCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxGroup as IxGroupElement, defineCustomElement as defineIxGroup } from "@siemens/ix/components/ix-group.js";

export type IxGroupEvents = {
    onSelectGroup: EventName<IxGroupCustomEvent<boolean>>,
    onSelectItem: EventName<IxGroupCustomEvent<number>>,
    onExpandedChanged: EventName<IxGroupCustomEvent<boolean>>
};

export const IxGroup: StencilReactComponent<IxGroupElement, IxGroupEvents, Components.IxGroup> = /*@__PURE__*/ createComponent<IxGroupElement, IxGroupEvents, Components.IxGroup>({
    tagName: 'ix-group',
    elementClass: IxGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSelectGroup: 'selectGroup',
        onSelectItem: 'selectItem',
        onExpandedChanged: 'expandedChanged'
    } as IxGroupEvents,
    defineCustomElement: defineIxGroup
});
