'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxGroupItemCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxGroupItem as IxGroupItemElement, defineCustomElement as defineIxGroupItem } from "@siemens/ix/components/ix-group-item.js";

export type IxGroupItemEvents = { onSelectedChanged: EventName<IxGroupItemCustomEvent<HTMLIxGroupItemElement>> };

export const IxGroupItem: StencilReactComponent<IxGroupItemElement, IxGroupItemEvents, Components.IxGroupItem> = /*@__PURE__*/ createComponent<IxGroupItemElement, IxGroupItemEvents, Components.IxGroupItem>({
    tagName: 'ix-group-item',
    elementClass: IxGroupItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelectedChanged: 'selectedChanged' } as IxGroupItemEvents,
    defineCustomElement: defineIxGroupItem
});
