'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxGroupCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxGroup as IxGroupElement } from "@siemens/ix/components/ix-group.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxGroupEvents = {
    onSelectGroup: EventName<IxGroupCustomEvent<boolean>>,
    onSelectItem: EventName<IxGroupCustomEvent<number>>,
    onExpandedChanged: EventName<IxGroupCustomEvent<boolean>>
};

export const IxGroup: StencilReactComponent<IxGroupElement, IxGroupEvents, Components.IxGroup> = /*@__PURE__*/ createComponent<IxGroupElement, IxGroupEvents, Components.IxGroup>({
    tagName: 'ix-group',
    properties: {
        suppressHeaderSelection: 'suppress-header-selection',
        header: 'header',
        subHeader: 'sub-header',
        expanded: 'expanded',
        selected: 'selected',
        index: 'index',
        expandOnHeaderClick: 'expand-on-header-click'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxGroup as StencilReactComponent<IxGroupElement, IxGroupEvents, Components.IxGroup>,
    serializeShadowRoot
});
