'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxInputCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxInput as IxInputElement, defineCustomElement as defineIxInput } from "@siemens/ix/components/ix-input.js";

export type IxInputEvents = {
    onValueChange: EventName<IxInputCustomEvent<string>>,
    onValidityStateChange: EventName<IxInputCustomEvent<ValidityState>>,
    onIxBlur: EventName<IxInputCustomEvent<void>>,
    onIxChange: EventName<IxInputCustomEvent<string>>
};

export const IxInput: StencilReactComponent<IxInputElement, IxInputEvents, Components.IxInput> = /*@__PURE__*/ createComponent<IxInputElement, IxInputEvents, Components.IxInput>({
    tagName: 'ix-input',
    elementClass: IxInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueChange: 'valueChange',
        onValidityStateChange: 'validityStateChange',
        onIxBlur: 'ixBlur',
        onIxChange: 'ixChange'
    } as IxInputEvents,
    defineCustomElement: defineIxInput
});
