'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxIconToggleButtonCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxIconToggleButton as IxIconToggleButtonElement, defineCustomElement as defineIxIconToggleButton } from "@siemens/ix/components/ix-icon-toggle-button.js";

export type IxIconToggleButtonEvents = { onPressedChange: EventName<IxIconToggleButtonCustomEvent<boolean>> };

export const IxIconToggleButton: StencilReactComponent<IxIconToggleButtonElement, IxIconToggleButtonEvents, Components.IxIconToggleButton> = /*@__PURE__*/ createComponent<IxIconToggleButtonElement, IxIconToggleButtonEvents, Components.IxIconToggleButton>({
    tagName: 'ix-icon-toggle-button',
    elementClass: IxIconToggleButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onPressedChange: 'pressedChange' } as IxIconToggleButtonEvents,
    defineCustomElement: defineIxIconToggleButton
});
