'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxModalHeaderCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxModalHeader as IxModalHeaderElement, defineCustomElement as defineIxModalHeader } from "@siemens/ix/components/ix-modal-header.js";

export type IxModalHeaderEvents = { onCloseClick: EventName<IxModalHeaderCustomEvent<MouseEvent>> };

export const IxModalHeader: StencilReactComponent<IxModalHeaderElement, IxModalHeaderEvents, Components.IxModalHeader> = /*@__PURE__*/ createComponent<IxModalHeaderElement, IxModalHeaderEvents, Components.IxModalHeader>({
    tagName: 'ix-modal-header',
    elementClass: IxModalHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCloseClick: 'closeClick' } as IxModalHeaderEvents,
    defineCustomElement: defineIxModalHeader
});
