'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type CustomCloseEvent, type IxMenuAboutCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxMenuAbout as IxMenuAboutElement } from "@siemens/ix/components/ix-menu-about.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxMenuAboutEvents = {
    onTabChange: EventName<IxMenuAboutCustomEvent<string>>,
    onClose: EventName<IxMenuAboutCustomEvent<CustomCloseEvent>>
};

export const IxMenuAbout: StencilReactComponent<IxMenuAboutElement, IxMenuAboutEvents, Components.IxMenuAbout> = /*@__PURE__*/ createComponent<IxMenuAboutElement, IxMenuAboutEvents, Components.IxMenuAbout>({
    tagName: 'ix-menu-about',
    properties: {
        suppressLegacyTabs: 'suppress-legacy-tabs',
        activeTabKey: 'active-tab-key',
        label: 'label',
        ariaLabelCloseButton: 'aria-label-close-button',
        show: 'show'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxMenuAbout as StencilReactComponent<IxMenuAboutElement, IxMenuAboutEvents, Components.IxMenuAbout>,
    serializeShadowRoot
});
