'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxMessageBarCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxMessageBar as IxMessageBarElement } from "@siemens/ix/components/ix-message-bar.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxMessageBarEvents = {
    onClosedChange: EventName<IxMessageBarCustomEvent<any>>,
    onCloseAnimationCompleted: EventName<IxMessageBarCustomEvent<any>>
};

export const IxMessageBar: StencilReactComponent<IxMessageBarElement, IxMessageBarEvents, Components.IxMessageBar> = /*@__PURE__*/ createComponent<IxMessageBarElement, IxMessageBarEvents, Components.IxMessageBar>({
    tagName: 'ix-message-bar',
    properties: {
        type: 'type',
        persistent: 'persistent'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxMessageBar as StencilReactComponent<IxMessageBarElement, IxMessageBarEvents, Components.IxMessageBar>,
    serializeShadowRoot
});
