'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxModalCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxModal as IxModalElement, defineCustomElement as defineIxModal } from "@siemens/ix/components/ix-modal.js";

export type IxModalEvents = {
    onDialogClose: EventName<IxModalCustomEvent<any>>,
    onDialogDismiss: EventName<IxModalCustomEvent<any>>
};

export const IxModal: StencilReactComponent<IxModalElement, IxModalEvents, Components.IxModal> = /*@__PURE__*/ createComponent<IxModalElement, IxModalEvents, Components.IxModal>({
    tagName: 'ix-modal',
    elementClass: IxModalElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDialogClose: 'dialogClose',
        onDialogDismiss: 'dialogDismiss'
    } as IxModalEvents,
    defineCustomElement: defineIxModal
});
