'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type CustomCloseEvent, type IxMenuSettingsCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxMenuSettings as IxMenuSettingsElement } from "@siemens/ix/components/ix-menu-settings.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxMenuSettingsEvents = {
    onTabChange: EventName<IxMenuSettingsCustomEvent<string>>,
    onClose: EventName<IxMenuSettingsCustomEvent<CustomCloseEvent>>
};

export const IxMenuSettings: StencilReactComponent<IxMenuSettingsElement, IxMenuSettingsEvents, Components.IxMenuSettings> = /*@__PURE__*/ createComponent<IxMenuSettingsElement, IxMenuSettingsEvents, Components.IxMenuSettings>({
    tagName: 'ix-menu-settings',
    properties: {
        suppressLegacyTabs: 'suppress-legacy-tabs',
        activeTabKey: 'active-tab-key',
        label: 'label',
        ariaLabelCloseButton: 'aria-label-close-button',
        show: 'show'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxMenuSettings as StencilReactComponent<IxMenuSettingsElement, IxMenuSettingsEvents, Components.IxMenuSettings>,
    serializeShadowRoot
});
