'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxModalHeaderCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxModalHeader as IxModalHeaderElement } from "@siemens/ix/components/ix-modal-header.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxModalHeaderEvents = { onCloseClick: EventName<IxModalHeaderCustomEvent<MouseEvent>> };

export const IxModalHeader: StencilReactComponent<IxModalHeaderElement, IxModalHeaderEvents, Components.IxModalHeader> = /*@__PURE__*/ createComponent<IxModalHeaderElement, IxModalHeaderEvents, Components.IxModalHeader>({
    tagName: 'ix-modal-header',
    properties: {
        hideClose: 'hide-close',
        icon: 'icon',
        ariaLabelIcon: 'aria-label-icon',
        ariaLabelCloseIconButton: 'aria-label-close-icon-button',
        iconColor: 'icon-color'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxModalHeader as StencilReactComponent<IxModalHeaderElement, IxModalHeaderEvents, Components.IxModalHeader>,
    serializeShadowRoot
});
