'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxNumberInputCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxNumberInput as IxNumberInputElement } from "@siemens/ix/components/ix-number-input.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxNumberInputEvents = {
    onValueChange: EventName<IxNumberInputCustomEvent<number>>,
    onValidityStateChange: EventName<IxNumberInputCustomEvent<ValidityState>>,
    onIxBlur: EventName<IxNumberInputCustomEvent<void>>,
    onIxChange: EventName<IxNumberInputCustomEvent<number>>
};

export const IxNumberInput: StencilReactComponent<IxNumberInputElement, IxNumberInputEvents, Components.IxNumberInput> = /*@__PURE__*/ createComponent<IxNumberInputElement, IxNumberInputEvents, Components.IxNumberInput>({
    tagName: 'ix-number-input',
    properties: {
        name: 'name',
        placeholder: 'placeholder',
        value: 'value',
        required: 'required',
        disabled: 'disabled',
        readonly: 'readonly',
        helperText: 'helper-text',
        infoText: 'info-text',
        showTextAsTooltip: 'show-text-as-tooltip',
        validText: 'valid-text',
        warningText: 'warning-text',
        label: 'label',
        invalidText: 'invalid-text',
        pattern: 'pattern',
        min: 'min',
        max: 'max',
        allowedCharactersPattern: 'allowed-characters-pattern',
        showStepperButtons: 'show-stepper-buttons',
        step: 'step',
        suppressSubmitOnEnter: 'suppress-submit-on-enter',
        textAlignment: 'text-alignment',
        allowEmptyValueChange: 'allow-empty-value-change'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxNumberInput as StencilReactComponent<IxNumberInputElement, IxNumberInputEvents, Components.IxNumberInput>,
    serializeShadowRoot
});
