'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxPaneLayout as IxPaneLayoutElement } from "@siemens/ix/components/ix-pane-layout.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxPaneLayoutEvents = NonNullable<unknown>;

export const IxPaneLayout: StencilReactComponent<IxPaneLayoutElement, IxPaneLayoutEvents, Components.IxPaneLayout> = /*@__PURE__*/ createComponent<IxPaneLayoutElement, IxPaneLayoutEvents, Components.IxPaneLayout>({
    tagName: 'ix-pane-layout',
    properties: {
        layout: 'layout',
        variant: 'variant',
        borderless: 'borderless'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxPaneLayout as StencilReactComponent<IxPaneLayoutElement, IxPaneLayoutEvents, Components.IxPaneLayout>,
    serializeShadowRoot
});
