'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxRadioGroupCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxRadioGroup as IxRadioGroupElement, defineCustomElement as defineIxRadioGroup } from "@siemens/ix/components/ix-radio-group.js";

export type IxRadioGroupEvents = { onValueChange: EventName<IxRadioGroupCustomEvent<string>> };

export const IxRadioGroup: StencilReactComponent<IxRadioGroupElement, IxRadioGroupEvents, Components.IxRadioGroup> = /*@__PURE__*/ createComponent<IxRadioGroupElement, IxRadioGroupEvents, Components.IxRadioGroup>({
    tagName: 'ix-radio-group',
    elementClass: IxRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as IxRadioGroupEvents,
    defineCustomElement: defineIxRadioGroup
});
