'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxRadioCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxRadio as IxRadioElement } from "@siemens/ix/components/ix-radio.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxRadioEvents = {
    onCheckedChange: EventName<IxRadioCustomEvent<boolean>>,
    onValueChange: EventName<IxRadioCustomEvent<string>>,
    onIxBlur: EventName<IxRadioCustomEvent<void>>
};

export const IxRadio: StencilReactComponent<IxRadioElement, IxRadioEvents, Components.IxRadio> = /*@__PURE__*/ createComponent<IxRadioElement, IxRadioEvents, Components.IxRadio>({
    tagName: 'ix-radio',
    properties: {
        name: 'name',
        value: 'value',
        label: 'label',
        disabled: 'disabled',
        checked: 'checked',
        required: 'required'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxRadio as StencilReactComponent<IxRadioElement, IxRadioEvents, Components.IxRadio>,
    serializeShadowRoot
});
