'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxRadioGroupCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxRadioGroup as IxRadioGroupElement } from "@siemens/ix/components/ix-radio-group.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxRadioGroupEvents = { onValueChange: EventName<IxRadioGroupCustomEvent<string>> };

export const IxRadioGroup: StencilReactComponent<IxRadioGroupElement, IxRadioGroupEvents, Components.IxRadioGroup> = /*@__PURE__*/ createComponent<IxRadioGroupElement, IxRadioGroupEvents, Components.IxRadioGroup>({
    tagName: 'ix-radio-group',
    properties: {
        helperText: 'helper-text',
        label: 'label',
        value: 'value',
        invalidText: 'invalid-text',
        infoText: 'info-text',
        warningText: 'warning-text',
        validText: 'valid-text',
        showTextAsTooltip: 'show-text-as-tooltip',
        direction: 'direction',
        required: 'required'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxRadioGroup as StencilReactComponent<IxRadioGroupElement, IxRadioGroupEvents, Components.IxRadioGroup>,
    serializeShadowRoot
});
