'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxRadioCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxRadio as IxRadioElement, defineCustomElement as defineIxRadio } from "@siemens/ix/components/ix-radio.js";

export type IxRadioEvents = {
    onCheckedChange: EventName<IxRadioCustomEvent<boolean>>,
    onValueChange: EventName<IxRadioCustomEvent<string>>,
    onIxBlur: EventName<IxRadioCustomEvent<void>>
};

export const IxRadio: StencilReactComponent<IxRadioElement, IxRadioEvents, Components.IxRadio> = /*@__PURE__*/ createComponent<IxRadioElement, IxRadioEvents, Components.IxRadio>({
    tagName: 'ix-radio',
    elementClass: IxRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCheckedChange: 'checkedChange',
        onValueChange: 'valueChange',
        onIxBlur: 'ixBlur'
    } as IxRadioEvents,
    defineCustomElement: defineIxRadio
});
