'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxSplitButtonCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxSplitButton as IxSplitButtonElement, defineCustomElement as defineIxSplitButton } from "@siemens/ix/components/ix-split-button.js";

export type IxSplitButtonEvents = { onButtonClick: EventName<IxSplitButtonCustomEvent<MouseEvent>> };

export const IxSplitButton: StencilReactComponent<IxSplitButtonElement, IxSplitButtonEvents, Components.IxSplitButton> = /*@__PURE__*/ createComponent<IxSplitButtonElement, IxSplitButtonEvents, Components.IxSplitButton>({
    tagName: 'ix-split-button',
    elementClass: IxSplitButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onButtonClick: 'buttonClick' } as IxSplitButtonEvents,
    defineCustomElement: defineIxSplitButton
});
