'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxSelectItemCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxSelectItem as IxSelectItemElement } from "@siemens/ix/components/ix-select-item.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxSelectItemEvents = { onItemClick: EventName<IxSelectItemCustomEvent<string>> };

export const IxSelectItem: StencilReactComponent<IxSelectItemElement, IxSelectItemEvents, Components.IxSelectItem> = /*@__PURE__*/ createComponent<IxSelectItemElement, IxSelectItemEvents, Components.IxSelectItem>({
    tagName: 'ix-select-item',
    properties: {
        ixFocusVisible: 'ix-focus-visible',
        disableAriaSelectHandling: 'disable-aria-select-handling',
        label: 'label',
        value: 'value',
        selected: 'selected',
        hover: 'hover'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxSelectItem as StencilReactComponent<IxSelectItemElement, IxSelectItemEvents, Components.IxSelectItem>,
    serializeShadowRoot
});
