'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxSliderCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxSlider as IxSliderElement, defineCustomElement as defineIxSlider } from "@siemens/ix/components/ix-slider.js";

export type IxSliderEvents = { onValueChange: EventName<IxSliderCustomEvent<number>> };

export const IxSlider: StencilReactComponent<IxSliderElement, IxSliderEvents, Components.IxSlider> = /*@__PURE__*/ createComponent<IxSliderElement, IxSliderEvents, Components.IxSlider>({
    tagName: 'ix-slider',
    elementClass: IxSliderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as IxSliderEvents,
    defineCustomElement: defineIxSlider
});
