'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxTabsCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxTabs as IxTabsElement, defineCustomElement as defineIxTabs } from "@siemens/ix/components/ix-tabs.js";

export type IxTabsEvents = {
    onTabChange: EventName<IxTabsCustomEvent<string | undefined>>,
    onTabClose: EventName<IxTabsCustomEvent<string | undefined>>
};

export const IxTabs: StencilReactComponent<IxTabsElement, IxTabsEvents, Components.IxTabs> = /*@__PURE__*/ createComponent<IxTabsElement, IxTabsEvents, Components.IxTabs>({
    tagName: 'ix-tabs',
    elementClass: IxTabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onTabChange: 'tabChange',
        onTabClose: 'tabClose'
    } as IxTabsEvents,
    defineCustomElement: defineIxTabs
});
