'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxTextareaCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxTextarea as IxTextareaElement, defineCustomElement as defineIxTextarea } from "@siemens/ix/components/ix-textarea.js";

export type IxTextareaEvents = {
    onValueChange: EventName<IxTextareaCustomEvent<string>>,
    onValidityStateChange: EventName<IxTextareaCustomEvent<ValidityState>>,
    onIxBlur: EventName<IxTextareaCustomEvent<void>>,
    onIxChange: EventName<IxTextareaCustomEvent<string>>
};

export const IxTextarea: StencilReactComponent<IxTextareaElement, IxTextareaEvents, Components.IxTextarea> = /*@__PURE__*/ createComponent<IxTextareaElement, IxTextareaEvents, Components.IxTextarea>({
    tagName: 'ix-textarea',
    elementClass: IxTextareaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueChange: 'valueChange',
        onValidityStateChange: 'validityStateChange',
        onIxBlur: 'ixBlur',
        onIxChange: 'ixChange'
    } as IxTextareaEvents,
    defineCustomElement: defineIxTextarea
});
