'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxTextareaCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxTextarea as IxTextareaElement } from "@siemens/ix/components/ix-textarea.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxTextareaEvents = {
    onValueChange: EventName<IxTextareaCustomEvent<string>>,
    onValidityStateChange: EventName<IxTextareaCustomEvent<ValidityState>>,
    onIxBlur: EventName<IxTextareaCustomEvent<void>>,
    onIxChange: EventName<IxTextareaCustomEvent<string>>
};

export const IxTextarea: StencilReactComponent<IxTextareaElement, IxTextareaEvents, Components.IxTextarea> = /*@__PURE__*/ createComponent<IxTextareaElement, IxTextareaEvents, Components.IxTextarea>({
    tagName: 'ix-textarea',
    properties: {
        name: 'name',
        placeholder: 'placeholder',
        value: 'value',
        required: 'required',
        disabled: 'disabled',
        readonly: 'readonly',
        helperText: 'helper-text',
        infoText: 'info-text',
        showTextAsTooltip: 'show-text-as-tooltip',
        validText: 'valid-text',
        warningText: 'warning-text',
        label: 'label',
        invalidText: 'invalid-text',
        textareaHeight: 'textarea-height',
        textareaWidth: 'textarea-width',
        textareaRows: 'textarea-rows',
        textareaCols: 'textarea-cols',
        resizeBehavior: 'resize-behavior',
        maxLength: 'max-length',
        minLength: 'min-length'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxTextarea as StencilReactComponent<IxTextareaElement, IxTextareaEvents, Components.IxTextarea>,
    serializeShadowRoot
});
