'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxToggleButtonCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxToggleButton as IxToggleButtonElement } from "@siemens/ix/components/ix-toggle-button.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxToggleButtonEvents = { onPressedChange: EventName<IxToggleButtonCustomEvent<boolean>> };

export const IxToggleButton: StencilReactComponent<IxToggleButtonElement, IxToggleButtonEvents, Components.IxToggleButton> = /*@__PURE__*/ createComponent<IxToggleButtonElement, IxToggleButtonEvents, Components.IxToggleButton>({
    tagName: 'ix-toggle-button',
    properties: {
        variant: 'variant',
        disabled: 'disabled',
        loading: 'loading',
        icon: 'icon',
        iconRight: 'icon-right',
        pressed: 'pressed'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxToggleButton as StencilReactComponent<IxToggleButtonElement, IxToggleButtonEvents, Components.IxToggleButton>,
    serializeShadowRoot
});
