'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxToastCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxToast as IxToastElement, defineCustomElement as defineIxToast } from "@siemens/ix/components/ix-toast.js";

export type IxToastEvents = { onCloseToast: EventName<IxToastCustomEvent<any>> };

export const IxToast: StencilReactComponent<IxToastElement, IxToastEvents, Components.IxToast> = /*@__PURE__*/ createComponent<IxToastElement, IxToastEvents, Components.IxToast>({
    tagName: 'ix-toast',
    elementClass: IxToastElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCloseToast: 'closeToast' } as IxToastEvents,
    defineCustomElement: defineIxToast
});
