'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@siemens/ix";
import { type IxTabsCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxTabs as IxTabsElement } from "@siemens/ix/components/ix-tabs.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": [], "default": "declarative-shadow-dom" };

export type IxTabsEvents = {
    onTabChange: EventName<IxTabsCustomEvent<string | undefined>>,
    onTabClose: EventName<IxTabsCustomEvent<string | undefined>>
};

export const IxTabs: StencilReactComponent<IxTabsElement, IxTabsEvents, Components.IxTabs> = /*@__PURE__*/ createComponent<IxTabsElement, IxTabsEvents, Components.IxTabs>({
    tagName: 'ix-tabs',
    properties: {
        small: 'small',
        rounded: 'rounded',
        layout: 'layout',
        placement: 'placement',
        ariaLabelMoreTabs: 'aria-label-more-tabs',
        activeTabKey: 'active-tab-key',
        keyboardNavigation: 'keyboard-navigation'
    },
    hydrateModule: import('@siemens/ix/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.IxTabs as StencilReactComponent<IxTabsElement, IxTabsEvents, Components.IxTabs>,
    serializeShadowRoot
});
