'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxTabItemCustomEvent, type TabClickDetail } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxTabItem as IxTabItemElement, defineCustomElement as defineIxTabItem } from "@siemens/ix/components/ix-tab-item.js";

export type IxTabItemEvents = {
    onTabClick: EventName<IxTabItemCustomEvent<TabClickDetail>>,
    onTabClose: EventName<IxTabItemCustomEvent<TabClickDetail>>
};

export const IxTabItem: StencilReactComponent<IxTabItemElement, IxTabItemEvents, Components.IxTabItem> = /*@__PURE__*/ createComponent<IxTabItemElement, IxTabItemEvents, Components.IxTabItem>({
    tagName: 'ix-tab-item',
    elementClass: IxTabItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onTabClick: 'tabClick',
        onTabClose: 'tabClose'
    } as IxTabItemEvents,
    defineCustomElement: defineIxTabItem
});
