'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxTimeInputCustomEvent, type TimeInputValidityState } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxTimeInput as IxTimeInputElement, defineCustomElement as defineIxTimeInput } from "@siemens/ix/components/ix-time-input.js";

export type IxTimeInputEvents = {
    onValueChange: EventName<IxTimeInputCustomEvent<string>>,
    onValidityStateChange: EventName<IxTimeInputCustomEvent<TimeInputValidityState>>,
    onIxChange: EventName<IxTimeInputCustomEvent<string>>
};

export const IxTimeInput: StencilReactComponent<IxTimeInputElement, IxTimeInputEvents, Components.IxTimeInput> = /*@__PURE__*/ createComponent<IxTimeInputElement, IxTimeInputEvents, Components.IxTimeInput>({
    tagName: 'ix-time-input',
    elementClass: IxTimeInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueChange: 'valueChange',
        onValidityStateChange: 'validityStateChange',
        onIxChange: 'ixChange'
    } as IxTimeInputEvents,
    defineCustomElement: defineIxTimeInput
});
