'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IxUploadCustomEvent } from "@siemens/ix";
import type { Components } from "@siemens/ix/components";
import { IxUpload as IxUploadElement, defineCustomElement as defineIxUpload } from "@siemens/ix/components/ix-upload.js";

export type IxUploadEvents = { onFilesChanged: EventName<IxUploadCustomEvent<Array<File>>> };

export const IxUpload: StencilReactComponent<IxUploadElement, IxUploadEvents, Components.IxUpload> = /*@__PURE__*/ createComponent<IxUploadElement, IxUploadEvents, Components.IxUpload>({
    tagName: 'ix-upload',
    elementClass: IxUploadElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onFilesChanged: 'filesChanged' } as IxUploadEvents,
    defineCustomElement: defineIxUpload
});
