/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxButton as IxButtonElement, defineCustomElement as defineIxButton } from "@siemens/ix/components/ix-button.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxButtonEvents = NonNullable<unknown>;

const IxButton: StencilReactComponent<IxButtonElement, IxButtonEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxButtonElement, IxButtonEvents>({
        tagName: 'ix-button',
        elementClass: IxButtonElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxButtonEvents,
        defineCustomElement: defineIxButton
    })
    : /*@__PURE__*/ createSSRComponent<IxButtonElement, IxButtonEvents>({
        tagName: 'ix-button',
        properties: {
            variant: 'variant',
            outline: 'outline',
            ghost: 'ghost',
            disabled: 'disabled',
            type: 'type',
            loading: 'loading',
            icon: 'icon',
            alignment: 'alignment',
            iconSize: 'icon-size'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxButton;
