/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxCardContent as IxCardContentElement, defineCustomElement as defineIxCardContent } from "@siemens/ix/components/ix-card-content.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxCardContentEvents = NonNullable<unknown>;

const IxCardContent: StencilReactComponent<IxCardContentElement, IxCardContentEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxCardContentElement, IxCardContentEvents>({
        tagName: 'ix-card-content',
        elementClass: IxCardContentElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxCardContentEvents,
        defineCustomElement: defineIxCardContent
    })
    : /*@__PURE__*/ createSSRComponent<IxCardContentElement, IxCardContentEvents>({
        tagName: 'ix-card-content',
        properties: {},
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxCardContent;
