'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type IxCardListCustomEvent } from "@siemens/ix";
import { IxCardList as IxCardListElement, defineCustomElement as defineIxCardList } from "@siemens/ix/components/ix-card-list.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxCardListEvents = {
    onCollapseChanged: EventName<CustomEvent<boolean>>,
    onShowAllClick: EventName<IxCardListCustomEvent<{
        nativeEvent: MouseEvent;
    }>>,
    onShowMoreCardClick: EventName<IxCardListCustomEvent<{
        nativeEvent: MouseEvent;
    }>>
};

const IxCardList: StencilReactComponent<IxCardListElement, IxCardListEvents> = /*@__PURE__*/ createComponent<IxCardListElement, IxCardListEvents>({
    tagName: 'ix-card-list',
    elementClass: IxCardListElement,
    react: React,
    events: {
        onCollapseChanged: 'collapseChanged',
        onShowAllClick: 'showAllClick',
        onShowMoreCardClick: 'showMoreCardClick'
    } as IxCardListEvents,
    defineCustomElement: defineIxCardList
});

export default IxCardList;
