/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxCard as IxCardElement, defineCustomElement as defineIxCard } from "@siemens/ix/components/ix-card.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxCardEvents = NonNullable<unknown>;

const IxCard: StencilReactComponent<IxCardElement, IxCardEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxCardElement, IxCardEvents>({
        tagName: 'ix-card',
        elementClass: IxCardElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxCardEvents,
        defineCustomElement: defineIxCard
    })
    : /*@__PURE__*/ createSSRComponent<IxCardElement, IxCardEvents>({
        tagName: 'ix-card',
        properties: {
            variant: 'variant',
            selected: 'selected'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxCard;
