/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type IxCardListCustomEvent } from "@siemens/ix";
import { IxCardList as IxCardListElement, defineCustomElement as defineIxCardList } from "@siemens/ix/components/ix-card-list.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxCardListEvents = {
    onCollapseChanged: EventName<CustomEvent<boolean>>,
    onShowAllClick: EventName<IxCardListCustomEvent<{
        nativeEvent: MouseEvent;
    }>>,
    onShowMoreCardClick: EventName<IxCardListCustomEvent<{
        nativeEvent: MouseEvent;
    }>>
};

const IxCardList: StencilReactComponent<IxCardListElement, IxCardListEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxCardListElement, IxCardListEvents>({
        tagName: 'ix-card-list',
        elementClass: IxCardListElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onCollapseChanged: 'collapseChanged',
            onShowAllClick: 'showAllClick',
            onShowMoreCardClick: 'showMoreCardClick'
        } as IxCardListEvents,
        defineCustomElement: defineIxCardList
    })
    : /*@__PURE__*/ createSSRComponent<IxCardListElement, IxCardListEvents>({
        tagName: 'ix-card-list',
        properties: {
            label: 'label',
            collapse: 'collapse',
            listStyle: 'list-style',
            maxVisibleCards: 'max-visible-cards',
            showAllCount: 'show-all-count',
            suppressOverflowHandling: 'suppress-overflow-handling',
            hideShowAll: 'hide-show-all',
            i18nShowAll: 'i-1-8n-show-all',
            i18nMoreCards: 'i-1-8n-more-cards'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxCardList;
