/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxCardTitle as IxCardTitleElement, defineCustomElement as defineIxCardTitle } from "@siemens/ix/components/ix-card-title.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxCardTitleEvents = NonNullable<unknown>;

const IxCardTitle: StencilReactComponent<IxCardTitleElement, IxCardTitleEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxCardTitleElement, IxCardTitleEvents>({
        tagName: 'ix-card-title',
        elementClass: IxCardTitleElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxCardTitleEvents,
        defineCustomElement: defineIxCardTitle
    })
    : /*@__PURE__*/ createSSRComponent<IxCardTitleElement, IxCardTitleEvents>({
        tagName: 'ix-card-title',
        properties: {},
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxCardTitle;
