/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxCheckbox as IxCheckboxElement, defineCustomElement as defineIxCheckbox } from "@siemens/ix/components/ix-checkbox.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxCheckboxEvents = {
    onCheckedChange: EventName<CustomEvent<boolean>>,
    onValueChange: EventName<CustomEvent<string>>
};

const IxCheckbox: StencilReactComponent<IxCheckboxElement, IxCheckboxEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxCheckboxElement, IxCheckboxEvents>({
        tagName: 'ix-checkbox',
        elementClass: IxCheckboxElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onCheckedChange: 'checkedChange',
            onValueChange: 'valueChange'
        } as IxCheckboxEvents,
        defineCustomElement: defineIxCheckbox
    })
    : /*@__PURE__*/ createSSRComponent<IxCheckboxElement, IxCheckboxEvents>({
        tagName: 'ix-checkbox',
        properties: {
            name: 'name',
            value: 'value',
            label: 'label',
            checked: 'checked',
            disabled: 'disabled',
            indeterminate: 'indeterminate',
            required: 'required'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxCheckbox;
