/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxChip as IxChipElement, defineCustomElement as defineIxChip } from "@siemens/ix/components/ix-chip.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxChipEvents = { onCloseChip: EventName<CustomEvent<any>> };

const IxChip: StencilReactComponent<IxChipElement, IxChipEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxChipElement, IxChipEvents>({
        tagName: 'ix-chip',
        elementClass: IxChipElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onCloseChip: 'closeChip' } as IxChipEvents,
        defineCustomElement: defineIxChip
    })
    : /*@__PURE__*/ createSSRComponent<IxChipElement, IxChipEvents>({
        tagName: 'ix-chip',
        properties: {
            variant: 'variant',
            active: 'active',
            closable: 'closable',
            icon: 'icon',
            background: 'background',
            chipColor: 'chip-color',
            outline: 'outline'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxChip;
