/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxContentHeader as IxContentHeaderElement, defineCustomElement as defineIxContentHeader } from "@siemens/ix/components/ix-content-header.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxContentHeaderEvents = { onBackButtonClick: EventName<CustomEvent<void>> };

const IxContentHeader: StencilReactComponent<IxContentHeaderElement, IxContentHeaderEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxContentHeaderElement, IxContentHeaderEvents>({
        tagName: 'ix-content-header',
        elementClass: IxContentHeaderElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBackButtonClick: 'backButtonClick' } as IxContentHeaderEvents,
        defineCustomElement: defineIxContentHeader
    })
    : /*@__PURE__*/ createSSRComponent<IxContentHeaderElement, IxContentHeaderEvents>({
        tagName: 'ix-content-header',
        properties: {
            variant: 'variant',
            headerTitle: 'header-title',
            headerSubtitle: 'header-subtitle',
            hasBackButton: 'has-back-button'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxContentHeader;
