/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type DateInputValidityState, type IxDateInputCustomEvent } from "@siemens/ix";
import { IxDateInput as IxDateInputElement, defineCustomElement as defineIxDateInput } from "@siemens/ix/components/ix-date-input.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxDateInputEvents = {
    onValueChange: EventName<CustomEvent<string>>,
    onValidityStateChange: EventName<IxDateInputCustomEvent<DateInputValidityState>>
};

const IxDateInput: StencilReactComponent<IxDateInputElement, IxDateInputEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxDateInputElement, IxDateInputEvents>({
        tagName: 'ix-date-input',
        elementClass: IxDateInputElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onValueChange: 'valueChange',
            onValidityStateChange: 'validityStateChange'
        } as IxDateInputEvents,
        defineCustomElement: defineIxDateInput
    })
    : /*@__PURE__*/ createSSRComponent<IxDateInputElement, IxDateInputEvents>({
        tagName: 'ix-date-input',
        properties: {
            name: 'name',
            placeholder: 'placeholder',
            value: 'value',
            locale: 'locale',
            format: 'format',
            required: 'required',
            helperText: 'helper-text',
            label: 'label',
            invalidText: 'invalid-text',
            readonly: 'readonly',
            disabled: 'disabled',
            infoText: 'info-text',
            warningText: 'warning-text',
            validText: 'valid-text',
            showTextAsTooltip: 'show-text-as-tooltip',
            i18nErrorDateUnparsable: 'i18n-error-date-unparsable'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxDateInput;
