/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type DateTimeDateChangeEvent, type DateTimeSelectEvent, type IxDatetimePickerCustomEvent } from "@siemens/ix";
import { IxDatetimePicker as IxDatetimePickerElement, defineCustomElement as defineIxDatetimePicker } from "@siemens/ix/components/ix-datetime-picker.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxDatetimePickerEvents = {
    onTimeChange: EventName<CustomEvent<string>>,
    onDateChange: EventName<IxDatetimePickerCustomEvent<DateTimeDateChangeEvent>>,
    onDateSelect: EventName<IxDatetimePickerCustomEvent<DateTimeSelectEvent>>
};

const IxDatetimePicker: StencilReactComponent<IxDatetimePickerElement, IxDatetimePickerEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxDatetimePickerElement, IxDatetimePickerEvents>({
        tagName: 'ix-datetime-picker',
        elementClass: IxDatetimePickerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onTimeChange: 'timeChange',
            onDateChange: 'dateChange',
            onDateSelect: 'dateSelect'
        } as IxDatetimePickerEvents,
        defineCustomElement: defineIxDatetimePicker
    })
    : /*@__PURE__*/ createSSRComponent<IxDatetimePickerElement, IxDatetimePickerEvents>({
        tagName: 'ix-datetime-picker',
        properties: {
            range: 'range',
            showHour: 'show-hour',
            showMinutes: 'show-minutes',
            showSeconds: 'show-seconds',
            minDate: 'min-date',
            maxDate: 'max-date',
            dateFormat: 'date-format',
            timeFormat: 'time-format',
            from: 'from',
            to: 'to',
            time: 'time',
            showTimeReference: 'show-time-reference',
            timeReference: 'time-reference',
            i18nDone: 'i18n-done',
            weekStartIndex: 'week-start-index',
            locale: 'locale'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxDatetimePicker;
