/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxDropdownButton as IxDropdownButtonElement, defineCustomElement as defineIxDropdownButton } from "@siemens/ix/components/ix-dropdown-button.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxDropdownButtonEvents = NonNullable<unknown>;

const IxDropdownButton: StencilReactComponent<IxDropdownButtonElement, IxDropdownButtonEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxDropdownButtonElement, IxDropdownButtonEvents>({
        tagName: 'ix-dropdown-button',
        elementClass: IxDropdownButtonElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxDropdownButtonEvents,
        defineCustomElement: defineIxDropdownButton
    })
    : /*@__PURE__*/ createSSRComponent<IxDropdownButtonElement, IxDropdownButtonEvents>({
        tagName: 'ix-dropdown-button',
        properties: {
            variant: 'variant',
            outline: 'outline',
            ghost: 'ghost',
            disabled: 'disabled',
            label: 'label',
            icon: 'icon',
            closeBehavior: 'close-behavior',
            placement: 'placement'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxDropdownButton;
