/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxDrawer as IxDrawerElement, defineCustomElement as defineIxDrawer } from "@siemens/ix/components/ix-drawer.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxDrawerEvents = {
    onOpen: EventName<CustomEvent<any>>,
    onDrawerClose: EventName<CustomEvent<any>>
};

const IxDrawer: StencilReactComponent<IxDrawerElement, IxDrawerEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxDrawerElement, IxDrawerEvents>({
        tagName: 'ix-drawer',
        elementClass: IxDrawerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onOpen: 'open',
            onDrawerClose: 'drawerClose'
        } as IxDrawerEvents,
        defineCustomElement: defineIxDrawer
    })
    : /*@__PURE__*/ createSSRComponent<IxDrawerElement, IxDrawerEvents>({
        tagName: 'ix-drawer',
        properties: {
            show: 'show',
            closeOnClickOutside: 'close-on-click-outside',
            fullHeight: 'full-height',
            minWidth: 'min-width',
            maxWidth: 'max-width',
            width: 'width'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxDrawer;
