/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxDropdownQuickActions as IxDropdownQuickActionsElement, defineCustomElement as defineIxDropdownQuickActions } from "@siemens/ix/components/ix-dropdown-quick-actions.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxDropdownQuickActionsEvents = NonNullable<unknown>;

const IxDropdownQuickActions: StencilReactComponent<IxDropdownQuickActionsElement, IxDropdownQuickActionsEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxDropdownQuickActionsElement, IxDropdownQuickActionsEvents>({
        tagName: 'ix-dropdown-quick-actions',
        elementClass: IxDropdownQuickActionsElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxDropdownQuickActionsEvents,
        defineCustomElement: defineIxDropdownQuickActions
    })
    : /*@__PURE__*/ createSSRComponent<IxDropdownQuickActionsElement, IxDropdownQuickActionsEvents>({
        tagName: 'ix-dropdown-quick-actions',
        properties: {},
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxDropdownQuickActions;
