/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxEventListItem as IxEventListItemElement, defineCustomElement as defineIxEventListItem } from "@siemens/ix/components/ix-event-list-item.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxEventListItemEvents = { onItemClick: EventName<CustomEvent<any>> };

const IxEventListItem: StencilReactComponent<IxEventListItemElement, IxEventListItemEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxEventListItemElement, IxEventListItemEvents>({
        tagName: 'ix-event-list-item',
        elementClass: IxEventListItemElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onItemClick: 'itemClick' } as IxEventListItemEvents,
        defineCustomElement: defineIxEventListItem
    })
    : /*@__PURE__*/ createSSRComponent<IxEventListItemElement, IxEventListItemEvents>({
        tagName: 'ix-event-list-item',
        properties: {
            itemColor: 'item-color',
            selected: 'selected',
            disabled: 'disabled',
            chevron: 'chevron'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxEventListItem;
