/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxEventList as IxEventListElement, defineCustomElement as defineIxEventList } from "@siemens/ix/components/ix-event-list.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxEventListEvents = NonNullable<unknown>;

const IxEventList: StencilReactComponent<IxEventListElement, IxEventListEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxEventListElement, IxEventListEvents>({
        tagName: 'ix-event-list',
        elementClass: IxEventListElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxEventListEvents,
        defineCustomElement: defineIxEventList
    })
    : /*@__PURE__*/ createSSRComponent<IxEventListElement, IxEventListEvents>({
        tagName: 'ix-event-list',
        properties: {
            itemHeight: 'item-height',
            compact: 'compact',
            animated: 'animated',
            chevron: 'chevron'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxEventList;
