/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxExpandingSearch as IxExpandingSearchElement, defineCustomElement as defineIxExpandingSearch } from "@siemens/ix/components/ix-expanding-search.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxExpandingSearchEvents = { onValueChange: EventName<CustomEvent<string>> };

const IxExpandingSearch: StencilReactComponent<IxExpandingSearchElement, IxExpandingSearchEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxExpandingSearchElement, IxExpandingSearchEvents>({
        tagName: 'ix-expanding-search',
        elementClass: IxExpandingSearchElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onValueChange: 'valueChange' } as IxExpandingSearchEvents,
        defineCustomElement: defineIxExpandingSearch
    })
    : /*@__PURE__*/ createSSRComponent<IxExpandingSearchElement, IxExpandingSearchEvents>({
        tagName: 'ix-expanding-search',
        properties: {
            icon: 'icon',
            placeholder: 'placeholder',
            value: 'value',
            fullWidth: 'full-width'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxExpandingSearch;
