/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxFilterChip as IxFilterChipElement, defineCustomElement as defineIxFilterChip } from "@siemens/ix/components/ix-filter-chip.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxFilterChipEvents = { onCloseClick: EventName<CustomEvent<void>> };

const IxFilterChip: StencilReactComponent<IxFilterChipElement, IxFilterChipEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxFilterChipElement, IxFilterChipEvents>({
        tagName: 'ix-filter-chip',
        elementClass: IxFilterChipElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onCloseClick: 'closeClick' } as IxFilterChipEvents,
        defineCustomElement: defineIxFilterChip
    })
    : /*@__PURE__*/ createSSRComponent<IxFilterChipElement, IxFilterChipEvents>({
        tagName: 'ix-filter-chip',
        properties: {
            disabled: 'disabled',
            readonly: 'readonly'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxFilterChip;
