/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxFlipTileContent as IxFlipTileContentElement, defineCustomElement as defineIxFlipTileContent } from "@siemens/ix/components/ix-flip-tile-content.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxFlipTileContentEvents = NonNullable<unknown>;

const IxFlipTileContent: StencilReactComponent<IxFlipTileContentElement, IxFlipTileContentEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxFlipTileContentElement, IxFlipTileContentEvents>({
        tagName: 'ix-flip-tile-content',
        elementClass: IxFlipTileContentElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxFlipTileContentEvents,
        defineCustomElement: defineIxFlipTileContent
    })
    : /*@__PURE__*/ createSSRComponent<IxFlipTileContentElement, IxFlipTileContentEvents>({
        tagName: 'ix-flip-tile-content',
        properties: { contentVisible: 'content-visible' },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxFlipTileContent;
