/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type IxGroupItemCustomEvent } from "@siemens/ix";
import { IxGroupItem as IxGroupItemElement, defineCustomElement as defineIxGroupItem } from "@siemens/ix/components/ix-group-item.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxGroupItemEvents = { onSelectedChanged: EventName<IxGroupItemCustomEvent<HTMLIxGroupItemElement>> };

const IxGroupItem: StencilReactComponent<IxGroupItemElement, IxGroupItemEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxGroupItemElement, IxGroupItemEvents>({
        tagName: 'ix-group-item',
        elementClass: IxGroupItemElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onSelectedChanged: 'selectedChanged' } as IxGroupItemEvents,
        defineCustomElement: defineIxGroupItem
    })
    : /*@__PURE__*/ createSSRComponent<IxGroupItemElement, IxGroupItemEvents>({
        tagName: 'ix-group-item',
        properties: {
            icon: 'icon',
            text: 'text',
            secondaryText: 'secondary-text',
            suppressSelection: 'suppress-selection',
            selected: 'selected',
            focusable: 'focusable',
            index: 'index'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxGroupItem;
