/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxIconButton as IxIconButtonElement, defineCustomElement as defineIxIconButton } from "@siemens/ix/components/ix-icon-button.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxIconButtonEvents = NonNullable<unknown>;

const IxIconButton: StencilReactComponent<IxIconButtonElement, IxIconButtonEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxIconButtonElement, IxIconButtonEvents>({
        tagName: 'ix-icon-button',
        elementClass: IxIconButtonElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxIconButtonEvents,
        defineCustomElement: defineIxIconButton
    })
    : /*@__PURE__*/ createSSRComponent<IxIconButtonElement, IxIconButtonEvents>({
        tagName: 'ix-icon-button',
        properties: {
            a11yLabel: 'a11y-label',
            variant: 'variant',
            outline: 'outline',
            ghost: 'ghost',
            oval: 'oval',
            icon: 'icon',
            size: 'size',
            iconColor: 'icon-color',
            disabled: 'disabled',
            type: 'type',
            loading: 'loading'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxIconButton;
