/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxKpi as IxKpiElement, defineCustomElement as defineIxKpi } from "@siemens/ix/components/ix-kpi.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxKpiEvents = NonNullable<unknown>;

const IxKpi: StencilReactComponent<IxKpiElement, IxKpiEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxKpiElement, IxKpiEvents>({
        tagName: 'ix-kpi',
        elementClass: IxKpiElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxKpiEvents,
        defineCustomElement: defineIxKpi
    })
    : /*@__PURE__*/ createSSRComponent<IxKpiElement, IxKpiEvents>({
        tagName: 'ix-kpi',
        properties: {
            label: 'label',
            value: 'value',
            unit: 'unit',
            state: 'state',
            orientation: 'orientation'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxKpi;
