/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxLayoutGrid as IxLayoutGridElement, defineCustomElement as defineIxLayoutGrid } from "@siemens/ix/components/ix-layout-grid.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxLayoutGridEvents = NonNullable<unknown>;

const IxLayoutGrid: StencilReactComponent<IxLayoutGridElement, IxLayoutGridEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxLayoutGridElement, IxLayoutGridEvents>({
        tagName: 'ix-layout-grid',
        elementClass: IxLayoutGridElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxLayoutGridEvents,
        defineCustomElement: defineIxLayoutGrid
    })
    : /*@__PURE__*/ createSSRComponent<IxLayoutGridElement, IxLayoutGridEvents>({
        tagName: 'ix-layout-grid',
        properties: {
            noMargin: 'no-margin',
            gap: 'gap',
            columns: 'columns'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxLayoutGrid;
