/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxLinkButton as IxLinkButtonElement, defineCustomElement as defineIxLinkButton } from "@siemens/ix/components/ix-link-button.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxLinkButtonEvents = NonNullable<unknown>;

const IxLinkButton: StencilReactComponent<IxLinkButtonElement, IxLinkButtonEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxLinkButtonElement, IxLinkButtonEvents>({
        tagName: 'ix-link-button',
        elementClass: IxLinkButtonElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxLinkButtonEvents,
        defineCustomElement: defineIxLinkButton
    })
    : /*@__PURE__*/ createSSRComponent<IxLinkButtonElement, IxLinkButtonEvents>({
        tagName: 'ix-link-button',
        properties: {
            disabled: 'disabled',
            url: 'url',
            target: 'target'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxLinkButton;
