/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxMapNavigation as IxMapNavigationElement, defineCustomElement as defineIxMapNavigation } from "@siemens/ix/components/ix-map-navigation.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxMapNavigationEvents = {
    onNavigationToggled: EventName<CustomEvent<boolean>>,
    onContextMenuClick: EventName<CustomEvent<void>>
};

const IxMapNavigation: StencilReactComponent<IxMapNavigationElement, IxMapNavigationEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxMapNavigationElement, IxMapNavigationEvents>({
        tagName: 'ix-map-navigation',
        elementClass: IxMapNavigationElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onNavigationToggled: 'navigationToggled',
            onContextMenuClick: 'contextMenuClick'
        } as IxMapNavigationEvents,
        defineCustomElement: defineIxMapNavigation
    })
    : /*@__PURE__*/ createSSRComponent<IxMapNavigationElement, IxMapNavigationEvents>({
        tagName: 'ix-map-navigation',
        properties: {
            applicationName: 'application-name',
            navigationTitle: 'navigation-title',
            hideContextMenu: 'hide-context-menu'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxMapNavigation;
