'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { IxMapNavigationOverlay as IxMapNavigationOverlayElement, defineCustomElement as defineIxMapNavigationOverlay } from "@siemens/ix/components/ix-map-navigation-overlay.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxMapNavigationOverlayEvents = { onCloseClick: EventName<CustomEvent<any>> };

const IxMapNavigationOverlay: StencilReactComponent<IxMapNavigationOverlayElement, IxMapNavigationOverlayEvents> = /*@__PURE__*/ createComponent<IxMapNavigationOverlayElement, IxMapNavigationOverlayEvents>({
    tagName: 'ix-map-navigation-overlay',
    elementClass: IxMapNavigationOverlayElement,
    react: React,
    events: { onCloseClick: 'closeClick' } as IxMapNavigationOverlayEvents,
    defineCustomElement: defineIxMapNavigationOverlay
});

export default IxMapNavigationOverlay;
