/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxMenuItem as IxMenuItemElement, defineCustomElement as defineIxMenuItem } from "@siemens/ix/components/ix-menu-item.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxMenuItemEvents = NonNullable<unknown>;

const IxMenuItem: StencilReactComponent<IxMenuItemElement, IxMenuItemEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxMenuItemElement, IxMenuItemEvents>({
        tagName: 'ix-menu-item',
        elementClass: IxMenuItemElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxMenuItemEvents,
        defineCustomElement: defineIxMenuItem
    })
    : /*@__PURE__*/ createSSRComponent<IxMenuItemElement, IxMenuItemEvents>({
        tagName: 'ix-menu-item',
        properties: {
            label: 'label',
            home: 'home',
            bottom: 'bottom',
            icon: 'icon',
            notifications: 'notifications',
            active: 'active',
            disabled: 'disabled',
            isCategory: 'is-category'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxMenuItem;
