/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type CustomLabelChangeEvent, type IxMenuAboutItemCustomEvent } from "@siemens/ix";
import { IxMenuAboutItem as IxMenuAboutItemElement, defineCustomElement as defineIxMenuAboutItem } from "@siemens/ix/components/ix-menu-about-item.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxMenuAboutItemEvents = { onLabelChange: EventName<IxMenuAboutItemCustomEvent<CustomLabelChangeEvent>> };

const IxMenuAboutItem: StencilReactComponent<IxMenuAboutItemElement, IxMenuAboutItemEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxMenuAboutItemElement, IxMenuAboutItemEvents>({
        tagName: 'ix-menu-about-item',
        elementClass: IxMenuAboutItemElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onLabelChange: 'labelChange' } as IxMenuAboutItemEvents,
        defineCustomElement: defineIxMenuAboutItem
    })
    : /*@__PURE__*/ createSSRComponent<IxMenuAboutItemElement, IxMenuAboutItemEvents>({
        tagName: 'ix-menu-about-item',
        properties: { label: 'label' },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxMenuAboutItem;
