/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type CustomCloseEvent, type IxMenuSettingsCustomEvent } from "@siemens/ix";
import { IxMenuSettings as IxMenuSettingsElement, defineCustomElement as defineIxMenuSettings } from "@siemens/ix/components/ix-menu-settings.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxMenuSettingsEvents = { onClose: EventName<IxMenuSettingsCustomEvent<CustomCloseEvent>> };

const IxMenuSettings: StencilReactComponent<IxMenuSettingsElement, IxMenuSettingsEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxMenuSettingsElement, IxMenuSettingsEvents>({
        tagName: 'ix-menu-settings',
        elementClass: IxMenuSettingsElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onClose: 'close' } as IxMenuSettingsEvents,
        defineCustomElement: defineIxMenuSettings
    })
    : /*@__PURE__*/ createSSRComponent<IxMenuSettingsElement, IxMenuSettingsEvents>({
        tagName: 'ix-menu-settings',
        properties: {
            activeTabLabel: 'active-tab-label',
            label: 'label',
            show: 'show'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxMenuSettings;
