/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxMessageBar as IxMessageBarElement, defineCustomElement as defineIxMessageBar } from "@siemens/ix/components/ix-message-bar.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxMessageBarEvents = { onClosedChange: EventName<CustomEvent<any>> };

const IxMessageBar: StencilReactComponent<IxMessageBarElement, IxMessageBarEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxMessageBarElement, IxMessageBarEvents>({
        tagName: 'ix-message-bar',
        elementClass: IxMessageBarElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onClosedChange: 'closedChange' } as IxMessageBarEvents,
        defineCustomElement: defineIxMessageBar
    })
    : /*@__PURE__*/ createSSRComponent<IxMessageBarElement, IxMessageBarEvents>({
        tagName: 'ix-message-bar',
        properties: {
            type: 'type',
            dismissible: 'dismissible'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxMessageBar;
