/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type IxMenuAvatarItemCustomEvent } from "@siemens/ix";
import { IxMenuAvatarItem as IxMenuAvatarItemElement, defineCustomElement as defineIxMenuAvatarItem } from "@siemens/ix/components/ix-menu-avatar-item.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxMenuAvatarItemEvents = { onItemClick: EventName<IxMenuAvatarItemCustomEvent<MouseEvent>> };

const IxMenuAvatarItem: StencilReactComponent<IxMenuAvatarItemElement, IxMenuAvatarItemEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxMenuAvatarItemElement, IxMenuAvatarItemEvents>({
        tagName: 'ix-menu-avatar-item',
        elementClass: IxMenuAvatarItemElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onItemClick: 'itemClick' } as IxMenuAvatarItemEvents,
        defineCustomElement: defineIxMenuAvatarItem
    })
    : /*@__PURE__*/ createSSRComponent<IxMenuAvatarItemElement, IxMenuAvatarItemEvents>({
        tagName: 'ix-menu-avatar-item',
        properties: {
            icon: 'icon',
            label: 'label'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxMenuAvatarItem;
