/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxMenuAvatar as IxMenuAvatarElement, defineCustomElement as defineIxMenuAvatar } from "@siemens/ix/components/ix-menu-avatar.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxMenuAvatarEvents = { onLogoutClick: EventName<CustomEvent<any>> };

const IxMenuAvatar: StencilReactComponent<IxMenuAvatarElement, IxMenuAvatarEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxMenuAvatarElement, IxMenuAvatarEvents>({
        tagName: 'ix-menu-avatar',
        elementClass: IxMenuAvatarElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onLogoutClick: 'logoutClick' } as IxMenuAvatarEvents,
        defineCustomElement: defineIxMenuAvatar
    })
    : /*@__PURE__*/ createSSRComponent<IxMenuAvatarElement, IxMenuAvatarEvents>({
        tagName: 'ix-menu-avatar',
        properties: {
            top: 'top',
            bottom: 'bottom',
            image: 'image',
            initials: 'initials',
            i18nLogout: 'i-1-8n-logout',
            showLogoutButton: 'show-logout-button'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxMenuAvatar;
