/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type IxModalHeaderCustomEvent } from "@siemens/ix";
import { IxModalHeader as IxModalHeaderElement, defineCustomElement as defineIxModalHeader } from "@siemens/ix/components/ix-modal-header.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxModalHeaderEvents = { onCloseClick: EventName<IxModalHeaderCustomEvent<MouseEvent>> };

const IxModalHeader: StencilReactComponent<IxModalHeaderElement, IxModalHeaderEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxModalHeaderElement, IxModalHeaderEvents>({
        tagName: 'ix-modal-header',
        elementClass: IxModalHeaderElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onCloseClick: 'closeClick' } as IxModalHeaderEvents,
        defineCustomElement: defineIxModalHeader
    })
    : /*@__PURE__*/ createSSRComponent<IxModalHeaderElement, IxModalHeaderEvents>({
        tagName: 'ix-modal-header',
        properties: {
            hideClose: 'hide-close',
            icon: 'icon',
            iconColor: 'icon-color'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxModalHeader;
