'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type BorderlessChangedEvent, type ExpandedChangedEvent, type IxPaneCustomEvent, type VariantChangedEvent } from "@siemens/ix";
import { IxPane as IxPaneElement, defineCustomElement as defineIxPane } from "@siemens/ix/components/ix-pane.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxPaneEvents = {
    onExpandedChanged: EventName<IxPaneCustomEvent<ExpandedChangedEvent>>,
    onVariantChanged: EventName<IxPaneCustomEvent<VariantChangedEvent>>,
    onBorderlessChanged: EventName<IxPaneCustomEvent<BorderlessChangedEvent>>
};

const IxPane: StencilReactComponent<IxPaneElement, IxPaneEvents> = /*@__PURE__*/ createComponent<IxPaneElement, IxPaneEvents>({
    tagName: 'ix-pane',
    elementClass: IxPaneElement,
    react: React,
    events: {
        onExpandedChanged: 'expandedChanged',
        onVariantChanged: 'variantChanged',
        onBorderlessChanged: 'borderlessChanged'
    } as IxPaneEvents,
    defineCustomElement: defineIxPane
});

export default IxPane;
