/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxSelect as IxSelectElement, defineCustomElement as defineIxSelect } from "@siemens/ix/components/ix-select.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxSelectEvents = {
    onValueChange: EventName<CustomEvent<string | string[]>>,
    onInputChange: EventName<CustomEvent<string>>,
    onAddItem: EventName<CustomEvent<string>>,
    onIxBlur: EventName<CustomEvent<void>>
};

const IxSelect: StencilReactComponent<IxSelectElement, IxSelectEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxSelectElement, IxSelectEvents>({
        tagName: 'ix-select',
        elementClass: IxSelectElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onValueChange: 'valueChange',
            onInputChange: 'inputChange',
            onAddItem: 'addItem',
            onIxBlur: 'ixBlur'
        } as IxSelectEvents,
        defineCustomElement: defineIxSelect
    })
    : /*@__PURE__*/ createSSRComponent<IxSelectElement, IxSelectEvents>({
        tagName: 'ix-select',
        properties: {
            name: 'name',
            required: 'required',
            label: 'label',
            warningText: 'warning-text',
            infoText: 'info-text',
            invalidText: 'invalid-text',
            validText: 'valid-text',
            helperText: 'helper-text',
            showTextAsTooltip: 'show-text-as-tooltip',
            value: 'value',
            allowClear: 'allow-clear',
            mode: 'mode',
            editable: 'editable',
            disabled: 'disabled',
            readonly: 'readonly',
            i18nPlaceholder: 'i-1-8n-placeholder',
            i18nPlaceholderEditable: 'i-1-8n-placeholder-editable',
            i18nSelectListHeader: 'i-1-8n-select-list-header',
            i18nNoMatches: 'i-1-8n-no-matches',
            hideListHeader: 'hide-list-header'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxSelect;
