/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxSelectItem as IxSelectItemElement, defineCustomElement as defineIxSelectItem } from "@siemens/ix/components/ix-select-item.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxSelectItemEvents = { onItemClick: EventName<CustomEvent<string>> };

const IxSelectItem: StencilReactComponent<IxSelectItemElement, IxSelectItemEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxSelectItemElement, IxSelectItemEvents>({
        tagName: 'ix-select-item',
        elementClass: IxSelectItemElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onItemClick: 'itemClick' } as IxSelectItemEvents,
        defineCustomElement: defineIxSelectItem
    })
    : /*@__PURE__*/ createSSRComponent<IxSelectItemElement, IxSelectItemEvents>({
        tagName: 'ix-select-item',
        properties: {
            label: 'label',
            value: 'value',
            selected: 'selected',
            hover: 'hover'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxSelectItem;
