/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxSpinner as IxSpinnerElement, defineCustomElement as defineIxSpinner } from "@siemens/ix/components/ix-spinner.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxSpinnerEvents = NonNullable<unknown>;

const IxSpinner: StencilReactComponent<IxSpinnerElement, IxSpinnerEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxSpinnerElement, IxSpinnerEvents>({
        tagName: 'ix-spinner',
        elementClass: IxSpinnerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxSpinnerEvents,
        defineCustomElement: defineIxSpinner
    })
    : /*@__PURE__*/ createSSRComponent<IxSpinnerElement, IxSpinnerEvents>({
        tagName: 'ix-spinner',
        properties: {
            variant: 'variant',
            size: 'size',
            hideTrack: 'hide-track'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxSpinner;
