/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type IxSplitButtonCustomEvent } from "@siemens/ix";
import { IxSplitButton as IxSplitButtonElement, defineCustomElement as defineIxSplitButton } from "@siemens/ix/components/ix-split-button.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxSplitButtonEvents = { onButtonClick: EventName<IxSplitButtonCustomEvent<MouseEvent>> };

const IxSplitButton: StencilReactComponent<IxSplitButtonElement, IxSplitButtonEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxSplitButtonElement, IxSplitButtonEvents>({
        tagName: 'ix-split-button',
        elementClass: IxSplitButtonElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onButtonClick: 'buttonClick' } as IxSplitButtonEvents,
        defineCustomElement: defineIxSplitButton
    })
    : /*@__PURE__*/ createSSRComponent<IxSplitButtonElement, IxSplitButtonEvents>({
        tagName: 'ix-split-button',
        properties: {
            variant: 'variant',
            closeBehavior: 'close-behavior',
            outline: 'outline',
            ghost: 'ghost',
            label: 'label',
            icon: 'icon',
            splitIcon: 'split-icon',
            disabled: 'disabled',
            placement: 'placement'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxSplitButton;
