/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type IxTabItemCustomEvent, type TabClickDetail } from "@siemens/ix";
import { IxTabItem as IxTabItemElement, defineCustomElement as defineIxTabItem } from "@siemens/ix/components/ix-tab-item.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxTabItemEvents = { onTabClick: EventName<IxTabItemCustomEvent<TabClickDetail>> };

const IxTabItem: StencilReactComponent<IxTabItemElement, IxTabItemEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxTabItemElement, IxTabItemEvents>({
        tagName: 'ix-tab-item',
        elementClass: IxTabItemElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onTabClick: 'tabClick' } as IxTabItemEvents,
        defineCustomElement: defineIxTabItem
    })
    : /*@__PURE__*/ createSSRComponent<IxTabItemElement, IxTabItemEvents>({
        tagName: 'ix-tab-item',
        properties: {
            selected: 'selected',
            disabled: 'disabled',
            small: 'small',
            icon: 'icon',
            rounded: 'rounded',
            counter: 'counter',
            layout: 'layout',
            placement: 'placement'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxTabItem;
