/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { type IxTextareaCustomEvent } from "@siemens/ix";
import { IxTextarea as IxTextareaElement, defineCustomElement as defineIxTextarea } from "@siemens/ix/components/ix-textarea.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxTextareaEvents = {
    onValueChange: EventName<CustomEvent<string>>,
    onValidityStateChange: EventName<IxTextareaCustomEvent<ValidityState>>,
    onIxBlur: EventName<CustomEvent<void>>
};

const IxTextarea: StencilReactComponent<IxTextareaElement, IxTextareaEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxTextareaElement, IxTextareaEvents>({
        tagName: 'ix-textarea',
        elementClass: IxTextareaElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onValueChange: 'valueChange',
            onValidityStateChange: 'validityStateChange',
            onIxBlur: 'ixBlur'
        } as IxTextareaEvents,
        defineCustomElement: defineIxTextarea
    })
    : /*@__PURE__*/ createSSRComponent<IxTextareaElement, IxTextareaEvents>({
        tagName: 'ix-textarea',
        properties: {
            name: 'name',
            placeholder: 'placeholder',
            value: 'value',
            required: 'required',
            disabled: 'disabled',
            readonly: 'readonly',
            helperText: 'helper-text',
            infoText: 'info-text',
            showTextAsTooltip: 'show-text-as-tooltip',
            validText: 'valid-text',
            warningText: 'warning-text',
            label: 'label',
            invalidText: 'invalid-text',
            textareaHeight: 'textarea-height',
            textareaWidth: 'textarea-width',
            textareaRows: 'textarea-rows',
            textareaCols: 'textarea-cols',
            resizeBehavior: 'resize-behavior',
            maxLength: 'max-length',
            minLength: 'min-length'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxTextarea;
