/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxTimePicker as IxTimePickerElement, defineCustomElement as defineIxTimePicker } from "@siemens/ix/components/ix-time-picker.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxTimePickerEvents = {
    onTimeSelect: EventName<CustomEvent<string>>,
    onTimeChange: EventName<CustomEvent<string>>
};

const IxTimePicker: StencilReactComponent<IxTimePickerElement, IxTimePickerEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxTimePickerElement, IxTimePickerEvents>({
        tagName: 'ix-time-picker',
        elementClass: IxTimePickerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onTimeSelect: 'timeSelect',
            onTimeChange: 'timeChange'
        } as IxTimePickerEvents,
        defineCustomElement: defineIxTimePicker
    })
    : /*@__PURE__*/ createSSRComponent<IxTimePickerElement, IxTimePickerEvents>({
        tagName: 'ix-time-picker',
        properties: {
            format: 'format',
            corners: 'corners',
            standaloneAppearance: 'standalone-appearance',
            showHour: 'show-hour',
            showMinutes: 'show-minutes',
            showSeconds: 'show-seconds',
            time: 'time',
            timeReference: 'time-reference',
            textSelectTime: 'text-select-time',
            textTime: 'text-time'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxTimePicker;
