/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxTooltip as IxTooltipElement, defineCustomElement as defineIxTooltip } from "@siemens/ix/components/ix-tooltip.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxTooltipEvents = NonNullable<unknown>;

const IxTooltip: StencilReactComponent<IxTooltipElement, IxTooltipEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxTooltipElement, IxTooltipEvents>({
        tagName: 'ix-tooltip',
        elementClass: IxTooltipElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxTooltipEvents,
        defineCustomElement: defineIxTooltip
    })
    : /*@__PURE__*/ createSSRComponent<IxTooltipElement, IxTooltipEvents>({
        tagName: 'ix-tooltip',
        properties: {
            for: 'for',
            titleContent: 'title-content',
            interactive: 'interactive',
            placement: 'placement',
            showDelay: 'show-delay',
            hideDelay: 'hide-delay',
            animationFrame: 'animation-frame'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxTooltip;
