/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxToggle as IxToggleElement, defineCustomElement as defineIxToggle } from "@siemens/ix/components/ix-toggle.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxToggleEvents = { onCheckedChange: EventName<CustomEvent<boolean>> };

const IxToggle: StencilReactComponent<IxToggleElement, IxToggleEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxToggleElement, IxToggleEvents>({
        tagName: 'ix-toggle',
        elementClass: IxToggleElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onCheckedChange: 'checkedChange' } as IxToggleEvents,
        defineCustomElement: defineIxToggle
    })
    : /*@__PURE__*/ createSSRComponent<IxToggleElement, IxToggleEvents>({
        tagName: 'ix-toggle',
        properties: {
            name: 'name',
            value: 'value',
            checked: 'checked',
            disabled: 'disabled',
            indeterminate: 'indeterminate',
            textOn: 'text-on',
            textOff: 'text-off',
            textIndeterminate: 'text-indeterminate',
            hideText: 'hide-text',
            required: 'required'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxToggle;
