/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxWorkflowSteps as IxWorkflowStepsElement, defineCustomElement as defineIxWorkflowSteps } from "@siemens/ix/components/ix-workflow-steps.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxWorkflowStepsEvents = { onStepSelected: EventName<CustomEvent<number>> };

const IxWorkflowSteps: StencilReactComponent<IxWorkflowStepsElement, IxWorkflowStepsEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxWorkflowStepsElement, IxWorkflowStepsEvents>({
        tagName: 'ix-workflow-steps',
        elementClass: IxWorkflowStepsElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onStepSelected: 'stepSelected' } as IxWorkflowStepsEvents,
        defineCustomElement: defineIxWorkflowSteps
    })
    : /*@__PURE__*/ createSSRComponent<IxWorkflowStepsElement, IxWorkflowStepsEvents>({
        tagName: 'ix-workflow-steps',
        properties: {
            vertical: 'vertical',
            clickable: 'clickable',
            selectedIndex: 'selected-index'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxWorkflowSteps;
