/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { IxWorkflowStep as IxWorkflowStepElement, defineCustomElement as defineIxWorkflowStep } from "@siemens/ix/components/ix-workflow-step.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IxWorkflowStepEvents = NonNullable<unknown>;

const IxWorkflowStep: StencilReactComponent<IxWorkflowStepElement, IxWorkflowStepEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<IxWorkflowStepElement, IxWorkflowStepEvents>({
        tagName: 'ix-workflow-step',
        elementClass: IxWorkflowStepElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as IxWorkflowStepEvents,
        defineCustomElement: defineIxWorkflowStep
    })
    : /*@__PURE__*/ createSSRComponent<IxWorkflowStepElement, IxWorkflowStepEvents>({
        tagName: 'ix-workflow-step',
        properties: {
            vertical: 'vertical',
            disabled: 'disabled',
            status: 'status',
            clickable: 'clickable',
            selected: 'selected',
            position: 'position'
        },
        hydrateModule: import('@siemens/ix/hydrate')
    });

export default IxWorkflowStep;
