name: 'Push Remote'
description: 'Push Remote'
inputs:
  internal-name:
    default: 'core'

  branch-name: # id of input
    default: 'ix'

  commit_id:
    description: 'commit id'

  commit_message_prefix:
    default: 'Nightly build'

  commit_message:
    description: 'commit message'
    default: ''

  token:
    description: 'github pat'

runs:
  using: 'composite'
  steps:
    - name: Prepare ${{ inputs.branch-name }} repo
      uses: actions/checkout@v3
      with:
        path: 'nightly_store_${{ inputs.branch-name }}'
        ref: ${{ inputs.branch-name }}
        repository: 'danielleroux/ix-nightlies'
        token: ${{ inputs.token }}
        fetch-depth: 0
        persist-credentials: true

    - name: Copy build files
      shell: bash
      run: |
        ROOT_PATH=$(pwd)
        cd ./packages/${{ inputs.internal-name }}
        TAR_FILE=$(pnpm pack)
        tar -xf $TAR_FILE -C $ROOT_PATH/nightly_store_${{ inputs.branch-name }}

    - name: Push to remote
      shell: bash
      working-directory: nightly_store_${{ inputs.branch-name }}
      run: |
        git ls-files -z | xargs -0 rm -rf || true
        git ls-tree --name-only -d -r -z HEAD | sort -rz | xargs -0 rmdir || true
        mv ./package/* .
        rm -rf package
        git config --global user.name "ix builder [bot]"
        git config --global user.email "<>"
        git add -A
        if [[ $(git status --porcelain) == '' ]]; then
          echo "No changes. Push to remote skipped!"
        else
          git commit -m "${{ inputs.commit_message_prefix }} $(date +"%Y-%m-%d %T") - ${{ inputs.commit_id }} ${{ inputs.commit_message }}"
          git push
        fi
