name: 'Accessibility Tests'
description: 'Accessibility Tests'
runs:
  using: 'composite'
  steps:
    - name: Build
      shell: bash
      run: pnpm run build --cache-dir=.turbo --filter storybook-docs

    - name: Test
      uses: ./.github/workflows/actions/playwright-container
      with:
        run: pnpm --filter storybook-docs test.a11y
