/*
 * COPYRIGHT (c) Siemens AG 2018-2022 ALL RIGHTS RESERVED.
 */
export enum UploadFileState {
  SELECT_FILE = 'SELECT_FILE',
  LOADING = 'LOADING',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  UPLOAD_SUCCESSED = 'UPLOAD_SUCCESSED',
}
