name: Pull Request Preview Cleanup

on:
  pull_request:
    branches-ignore:
      - changeset-release/main
    types:
      - closed

concurrency: pr-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/turbo

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./packages/documentation/build
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: remove
