name: Deploy GitHub Page (prod)

on:
  workflow_dispatch:
    inputs:
        confirm_deployment:
          description: 'Please confirm deployment'
          required: true
          type: boolean

concurrency: deploy-gh-pages-${{ github.ref }}

jobs:
  deploy-gh-pages:
    if: ${{ inputs.confirm_deployment == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/turbo

      - name: Build
        run: pnpm build --cache-dir=.turbo --filter documentation
        env:
          FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
          CSC: ${{ secrets.READ_CSC_TOKEN }}

      - name: Deploy GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./packages/documentation/build
          clean-exclude: version-*

