name: Deploy GitHub Page (prod)

on:
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Please confirm deployment'
        required: true
        type: boolean

concurrency: deploy-gh-pages-${{ github.ref }}

jobs:
  deploy-gh-pages:
    if: ${{ inputs.confirm_deployment == true && github.repository == 'siemens/ix' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/turbo

      - name: Build
        run: pnpm build --cache-dir=.turbo --filter documentation --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
          CSC: ${{ secrets.READ_CSC_TOKEN }}

      - name: Deploy GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8
        with:
          folder: ./packages/documentation/build
          clean-exclude: version-*
