name: OSS

on:
  push:
    branches:
      - 'main'
      - 'release/*'
      - 'release-*'
      - changeset-release/main
  workflow_dispatch:

jobs:
  sbom:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/turbo

      - name: Create SBOM
        run: pnpm --filter oss-clearing start

      - uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.run_attempt }}
          path: |
            ./tooling/oss-clearing/sboms/
