name: SBOM creation

on:
  push:
    branches:
      - 'main'
      - 'release/*'
      - 'changeset-release/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/turbo

      - name: Build
        run: pnpm build --cache-dir=.turbo

  sbom:
    needs: [build]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/turbo
      - uses: ./.github/workflows/actions/sbom
